#Aether map design
#Sun Jul 19 20:03:39 JST 2026
alternateTheme=STONE_WOOD
description=(1,0) Abandoned Catacomb (lv5)
displayName=1_0_Abandoned Catacomb (lv5)
geometry.height.0=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.1=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.10=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.11=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.12=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.13=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.14=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.15=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.16=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.17=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.18=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.19=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.2=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.3=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.4=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.5=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.6=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.7=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.8=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.9=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
height=20
mobArea.0=,,,,,,,,,,,,,,,,,,,
mobArea.1=,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,,,,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,,zone_1,
mobArea.10=,zone_1,,zone_1,,,zone_1,,,,,,,,,,zone_1,,zone_1,
mobArea.11=,zone_1,,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,
mobArea.12=,zone_1,,,,,,,,,,,,,,,,,,
mobArea.13=,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,,zone_1,zone_1,zone_1,zone_1,,,,,,
mobArea.14=,zone_1,,,,,,,,,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,,,,
mobArea.15=,zone_1,zone_1,zone_1,zone_1,zone_1,zone_1,,,,zone_1,zone_1,zone_1,,zone_1,,,,,
mobArea.16=,zone_1,,,,,zone_1,,,,zone_1,zone_1,zone_1,,zone_1,,,,,
mobArea.17=,zone_1,,,,,zone_1,,,,,,,,zone_1,,,,,
mobArea.18=,zone_1,,,,,zone_1,zone_1,zone_1,,zone_1,zone_1,zone_1,zone_1,zone_1,,,,,
mobArea.19=,,,,,,,,,,,,,,,,,,,
mobArea.2=,zone_1,,,,,zone_1,,,,,,zone_1,,,,zone_1,,zone_1,
mobArea.3=,zone_1,,zone_1,,zone_1,zone_1,,,,zone_1,zone_1,zone_1,zone_1,zone_1,,zone_1,,zone_1,
mobArea.4=,zone_1,,zone_1,,zone_1,,,,,zone_1,,zone_1,,zone_1,,zone_1,,zone_1,
mobArea.5=,zone_1,,zone_1,,zone_1,zone_1,,,,zone_1,,,,zone_1,,zone_1,,zone_1,
mobArea.6=,zone_1,,zone_1,,,zone_1,,,,zone_1,zone_1,zone_1,,zone_1,,zone_1,,zone_1,
mobArea.7=,zone_1,,zone_1,,zone_1,zone_1,,,,zone_1,zone_1,zone_1,,zone_1,,zone_1,,zone_1,
mobArea.8=,zone_1,,zone_1,,zone_1,,,,,zone_1,,,,zone_1,,zone_1,,zone_1,
mobArea.9=,zone_1,,zone_1,,zone_1,zone_1,,,,zone_1,zone_1,zone_1,zone_1,zone_1,,zone_1,,zone_1,
musicPath=
paint.door.0=,,,,,,,,,,,,,,,,,,,
paint.door.1=,,,,,,,,,,,,,,,,,,,
paint.door.10=,,,,,,,,,,,,,,,,,,,
paint.door.11=,,,,,,,,,,,,,,,,,,,
paint.door.12=,,,,,,,,,,,,,,,,,,,
paint.door.13=,,,,,,,,,,,,,,,,,,,
paint.door.14=,,,,,,,,,,,,,,,,,,,
paint.door.15=,,,,,,,,,,,,,,,,,,,
paint.door.16=,,,,,,,,,,,,,,,,,,,
paint.door.17=,,,,,,,,,,,,,,,,,,,
paint.door.18=,,,,,,,,,,,,,,,,,,,
paint.door.19=,,,,,,,,,,,,,,,,,,,
paint.door.2=,,,,,,,,,,,,,,,,,,,
paint.door.3=,,,,,,,,,,,,,,,,,,,
paint.door.4=,,,,,,,,,,,,,,,,,,,
paint.door.5=,,,,,,,,,,,,,,,,,,,
paint.door.6=,,,,,,,,,,,,,,,,,,,
paint.door.7=,,,,,,,,,,,,,,,,,,,
paint.door.8=,,,,,,,,,,,,,,,,,,,
paint.door.9=,,,,,,,,,,,,,,,,,,,
paint.floor.0=,,,,,,,,,,,,,,,,,,,
paint.floor.1=,,,,,,,,,,,,,,,,,,,
paint.floor.10=,,,,,,,,,,,,,,,,,,,
paint.floor.11=,,,,,,,,,,,,,,,,,,,
paint.floor.12=,,,,,,,,,,,,,,,,,,,
paint.floor.13=,,,,,,,,,,,,,,,,,,,
paint.floor.14=,,,,,,,,,,,,,,,,,,,
paint.floor.15=,,,,,,,,,,,,,,,,,,,
paint.floor.16=,,,,,,,,,,,,,,,,,,,
paint.floor.17=,,,,,,,,,,,,,,,,,,,
paint.floor.18=,,,,,,,,,,,,,,,,,,,
paint.floor.19=,,,,,,,,,,,,,,,,,,,
paint.floor.2=,,,,,,,,,,,,,,,,,,,
paint.floor.3=,,,,,,,,,,,,,,,,,,,
paint.floor.4=,,,,,,,,,,,,,,,,,,,
paint.floor.5=,,,,,,,,,,,,,,,,,,,
paint.floor.6=,,,,,,,,,,,,,,,,,,,
paint.floor.7=,,,,,,,,,,,,,,,,,,,
paint.floor.8=,,,,,,,,,,,,,,,,,,,
paint.floor.9=,,,,,,,,,,,,,,,,,,,
paint.roof.0=,,,,,,,,,,,,,,,,,,,
paint.roof.1=,,,,,,,,,,,,,,,,,,,
paint.roof.10=,,,,,,,,,,,,,,,,,,,
paint.roof.11=,,,,,,,,,,,,,,,,,,,
paint.roof.12=,,,,,,,,,,,,,,,,,,,
paint.roof.13=,,,,,,,,,,,,,,,,,,,
paint.roof.14=,,,,,,,,,,,,,,,,,,,
paint.roof.15=,,,,,,,,,,,,,,,,,,,
paint.roof.16=,,,,,,,,,,,,,,,,,,,
paint.roof.17=,,,,,,,,,,,,,,,,,,,
paint.roof.18=,,,,,,,,,,,,,,,,,,,
paint.roof.19=,,,,,,,,,,,,,,,,,,,
paint.roof.2=,,,,,,,,,,,,,,,,,,,
paint.roof.3=,,,,,,,,,,,,,,,,,,,
paint.roof.4=,,,,,,,,,,,,,,,,,,,
paint.roof.5=,,,,,,,,,,,,,,,,,,,
paint.roof.6=,,,,,,,,,,,,,,,,,,,
paint.roof.7=,,,,,,,,,,,,,,,,,,,
paint.roof.8=,,,,,,,,,,,,,,,,,,,
paint.roof.9=,,,,,,,,,,,,,,,,,,,
paint.wall.0=,,,,,,,,,,,,,,,,,,,
paint.wall.1=,,,,,,,,,,,,,,,,,,,
paint.wall.10=,,,,,,,,,,,,,,,,,,,
paint.wall.11=,,,,,,,,,,,,,,,,,,,
paint.wall.12=,,,,,,,,,,,,,,,,,,,
paint.wall.13=,,,,,,,,,,,,,,,,,,,
paint.wall.14=,,,,,,,,,,,,,,,,,,,
paint.wall.15=,,,,,,,,,,,,,,,,,,,
paint.wall.16=,,,,,,,,,,,,,,,,,,,
paint.wall.17=,,,,,,,,,,,,,,,,,,,
paint.wall.18=,,,,,,,,,,,,,,,,,,,
paint.wall.19=,,,,,,,,,,,,,,,,,,,
paint.wall.2=,,,,,,,,,,,,,,,,,,,
paint.wall.3=,,,,,,,,,,,,,,,,,,,
paint.wall.4=,,,,,,,,,,,,,,,,,,,
paint.wall.5=,,,,,,,,,,,,,,,,,,,
paint.wall.6=,,,,,,,,,,,,,,,,,,,
paint.wall.7=,,,,,,,,,,,,,,,,,,,
paint.wall.8=,,,,,,,,,,,,,,,,,,,
paint.wall.9=,,,,,,,,,,,,,,,,,,,
placement.0.id=custom_mob_kobold_wizard
placement.0.kind=ENEMY
placement.0.x=10
placement.0.y=14
placement.1.id=custom_mob_kobold_champion
placement.1.kind=ENEMY
placement.1.x=12
placement.1.y=6
placement.2.id=custom_mob_kobold
placement.2.kind=ENEMY
placement.2.x=6
placement.2.y=9
placement.3.id=custom_mob_kobold
placement.3.kind=ENEMY
placement.3.x=3
placement.3.y=4
placement.4.id=custom_mob_kobold
placement.4.kind=ENEMY
placement.4.x=1
placement.4.y=1
placement.5.id=custom_mob_kobold
placement.5.kind=ENEMY
placement.5.x=18
placement.5.y=3
placement.6.id=map_link|assets/editor/worlds/overworld/world.properties|58|4
placement.6.kind=INTERACTION
placement.6.x=8
placement.6.y=0
placement.count=7
primaryTheme=STONE_WOOD
skyboxPath=
spawnX=8
spawnY=1
themes.0=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.1=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.10=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.11=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.12=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.13=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.14=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.15=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.16=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.17=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.18=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.19=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.2=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.3=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.4=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.5=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.6=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.7=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.8=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.9=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
tiles.0=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL
tiles.1=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL
tiles.10=WALL,FLOOR,WALL,FLOOR,WALL,WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL
tiles.11=WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.12=WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL
tiles.13=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL
tiles.14=WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL
tiles.15=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.16=WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.17=WALL,FLOOR,WALL,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.18=WALL,FLOOR,WALL,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,QUEST_DOOR_CLOSED,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL
tiles.19=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL
tiles.2=WALL,FLOOR,WALL,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL
tiles.3=WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.4=WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.5=WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.6=WALL,FLOOR,WALL,FLOOR,WALL,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.7=WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.8=WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL,WALL,FLOOR,WALL,FLOOR,WALL,WALL,WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
tiles.9=WALL,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,WALL,FLOOR,WALL
trigger.0.action.0.targetX=9
trigger.0.action.0.targetY=18
trigger.0.action.0.type=CLOSE_DOOR
trigger.0.action.count=1
trigger.0.fireMode=ON_ENTRY
trigger.0.id=Open Shortcut
trigger.0.oneShot=true
trigger.0.requiredQuestId=
trigger.0.requiredQuestStage=0
trigger.0.x=12
trigger.0.y=18
trigger.count=1
width=20
