#Aether map design
#Wed Jul 15 22:45:02 JST 2026
alternateTheme=SANDSTONE_GATE
description=
displayName=Bryan_TestMap
height=20
placement.0.id=FISHING_SHOAL
placement.0.kind=GATHERING_NODE
placement.0.x=18
placement.0.y=1
placement.1.id=MINERAL_ROCK_A
placement.1.kind=GATHERING_NODE
placement.1.x=16
placement.1.y=1
placement.10.id=POTION
placement.10.kind=ITEM
placement.10.x=1
placement.10.y=15
placement.11.id=BONES
placement.11.kind=ITEM
placement.11.x=1
placement.11.y=16
placement.12.id=SLIME
placement.12.kind=ITEM
placement.12.x=1
placement.12.y=17
placement.13.id=RAW_FISH
placement.13.kind=ITEM
placement.13.x=1
placement.13.y=18
placement.14.id=COOKED_FISH
placement.14.kind=ITEM
placement.14.x=3
placement.14.y=18
placement.15.id=COPPER_ORE
placement.15.kind=ITEM
placement.15.x=3
placement.15.y=17
placement.16.id=COPPER_BAR
placement.16.kind=ITEM
placement.16.x=3
placement.16.y=16
placement.17.id=IRON_SWORD
placement.17.kind=ITEM
placement.17.x=3
placement.17.y=15
placement.18.id=LEATHER_CAP
placement.18.kind=ITEM
placement.18.x=3
placement.18.y=14
placement.19.id=SILVER_RING
placement.19.kind=ITEM
placement.19.x=3
placement.19.y=13
placement.2.id=node_iron_rock
placement.2.kind=GATHERING_NODE
placement.2.x=16
placement.2.y=2
placement.20.id=custom_item_copper_platebody
placement.20.kind=ITEM
placement.20.x=3
placement.20.y=12
placement.21.id=custom_item_copper_helmet
placement.21.kind=ITEM
placement.21.x=5
placement.21.y=12
placement.22.id=custom_item_copper_platelegs
placement.22.kind=ITEM
placement.22.x=5
placement.22.y=13
placement.23.id=custom_item_iron_ore
placement.23.kind=ITEM
placement.23.x=5
placement.23.y=14
placement.24.id=custom_item_iron_bar
placement.24.kind=ITEM
placement.24.x=5
placement.24.y=15
placement.25.id=custom_item_coal
placement.25.kind=ITEM
placement.25.x=5
placement.25.y=16
placement.26.id=custom_item_coal_iron_mix
placement.26.kind=ITEM
placement.26.x=5
placement.26.y=17
placement.27.id=custom_item_steel_bar
placement.27.kind=ITEM
placement.27.x=5
placement.27.y=18
placement.28.id=custom_item_tin_ore
placement.28.kind=ITEM
placement.28.x=7
placement.28.y=18
placement.29.id=custom_item_tin_copper_mix
placement.29.kind=ITEM
placement.29.x=7
placement.29.y=17
placement.3.id=node_coal_rock
placement.3.kind=GATHERING_NODE
placement.3.x=16
placement.3.y=3
placement.30.id=custom_item_bronze_bar
placement.30.kind=ITEM
placement.30.x=7
placement.30.y=16
placement.31.id=custom_item_bronze_sword
placement.31.kind=ITEM
placement.31.x=7
placement.31.y=15
placement.32.id=custom_item_bronze_helmet
placement.32.kind=ITEM
placement.32.x=7
placement.32.y=14
placement.33.id=custom_item_bronze_platebody
placement.33.kind=ITEM
placement.33.x=7
placement.33.y=13
placement.34.id=custom_item_bronze_platelegs
placement.34.kind=ITEM
placement.34.x=7
placement.34.y=12
placement.35.id=custom_item_bronze_dagger
placement.35.kind=ITEM
placement.35.x=9
placement.35.y=12
placement.36.id=custom_item_iron_platelegs
placement.36.kind=ITEM
placement.36.x=9
placement.36.y=13
placement.37.id=custom_item_iron_platebody
placement.37.kind=ITEM
placement.37.x=9
placement.37.y=14
placement.38.id=custom_item_iron_helmet
placement.38.kind=ITEM
placement.38.x=9
placement.38.y=15
placement.39.id=custom_item_iron_dagger
placement.39.kind=ITEM
placement.39.x=9
placement.39.y=16
placement.4.id=CAMPFIRE
placement.4.kind=CRAFTING_NODE
placement.4.x=18
placement.4.y=18
placement.40.id=custom_item_copper_dagger
placement.40.kind=ITEM
placement.40.x=9
placement.40.y=17
placement.41.id=limb_kobold_head
placement.41.kind=ITEM
placement.41.x=9
placement.41.y=18
placement.42.id=limb_kobold_body
placement.42.kind=ITEM
placement.42.x=11
placement.42.y=18
placement.43.id=limb_kobold_left_arm
placement.43.kind=ITEM
placement.43.x=11
placement.43.y=17
placement.44.id=limb_kobold_right_arm
placement.44.kind=ITEM
placement.44.x=11
placement.44.y=16
placement.45.id=limb_kobold_legs
placement.45.kind=ITEM
placement.45.x=11
placement.45.y=15
placement.5.id=FURNACE
placement.5.kind=CRAFTING_NODE
placement.5.x=17
placement.5.y=18
placement.6.id=ANVIL
placement.6.kind=CRAFTING_NODE
placement.6.x=16
placement.6.y=18
placement.7.id=BURNT_FISH
placement.7.kind=ITEM
placement.7.x=1
placement.7.y=12
placement.8.id=custom_item_inert_stone
placement.8.kind=ITEM
placement.8.x=1
placement.8.y=13
placement.9.id=GOLD
placement.9.kind=ITEM
placement.9.x=1
placement.9.y=14
placement.count=46
primaryTheme=STONE_WOOD
spawnX=1
spawnY=1
themes.0=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.1=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.10=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.11=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.12=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.13=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.14=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.15=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.16=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.17=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.18=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.19=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.2=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.3=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.4=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.5=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.6=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.7=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.8=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.9=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
tiles.0=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL
tiles.1=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.10=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.11=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.12=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.13=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.14=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.15=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.16=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.17=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.18=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.19=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL
tiles.2=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.3=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.4=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.5=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.6=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.7=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.8=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.9=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
trigger.count=0
width=20
