#Aether map design
#Sat Jul 18 21:43:35 JST 2026
alternateTheme=STONE_WOOD
description=
displayName=new_map
geometry.height.0=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.1=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.10=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.11=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.2=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.3=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.4=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.5=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.6=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.7=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.8=1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.9=1,1,1,1,1,1,1,1,1,1,1,1,1,1
height=12
musicPath=
paint.door.0=,,,,,,,,,,,,,
paint.door.1=,,,,,,,,,,,,,
paint.door.10=,,,,,,,,,,,,,
paint.door.11=,,,,,,,,,,,,,
paint.door.2=,,,,,,,,,,,,,
paint.door.3=,,,,,,,,,,,,,
paint.door.4=,,,,,,,,,,,,,
paint.door.5=,,,,,,,,,,,,,
paint.door.6=,,,,,,,,,,,,,
paint.door.7=,,,,,,,,,,,,,
paint.door.8=,,,,,,,,,,,,,
paint.door.9=,,,,,,,,,,,,,
paint.floor.0=,,,,,,,,,,,,,
paint.floor.1=,,,,,,,,,,,,,
paint.floor.10=,,,,,,,,,,,,,
paint.floor.11=,,,,,,,,,,,,,
paint.floor.2=,,,,,,,,,,,,,
paint.floor.3=,,,,,,,,,,,,,
paint.floor.4=,,,,,,,,,,,,,
paint.floor.5=,,,,,,,,,,,,,
paint.floor.6=,,,,,,,,,,,,,
paint.floor.7=,,,,,,,,,,,,,
paint.floor.8=,,,,,,,,,,,,,
paint.floor.9=,,,,,,,,,,,,,
paint.roof.0=,,,,,,,,,,,,,
paint.roof.1=,,,,,,,,,,,,,
paint.roof.10=,,,,,,,,,,,,,
paint.roof.11=,,,,,,,,,,,,,
paint.roof.2=,,,,,,,,,,,,,
paint.roof.3=,,,,,,,,,,,,,
paint.roof.4=,,,,,,,,,,,,,
paint.roof.5=,,,,,,,,,,,,,
paint.roof.6=,,,,,,,,,,,,,
paint.roof.7=,,,,,,,,,,,,,
paint.roof.8=,,,,,,,,,,,,,
paint.roof.9=,,,,,,,,,,,,,
paint.wall.0=,,,,,,,,,,,,,
paint.wall.1=,,,,,,,,,,,,,
paint.wall.10=,,,,,,,,,,,,,
paint.wall.11=,,,,,,,,,,,,,
paint.wall.2=,,,,,,,,,,,,,
paint.wall.3=,,,,,,,,,,,,,
paint.wall.4=,,,,,,,,,,,,,
paint.wall.5=,,,,,,,,,,,,,
paint.wall.6=,,,,,,,,,,,,,
paint.wall.7=,,,,,,,,,,,,,
paint.wall.8=,,,,,,,,,,,,,
paint.wall.9=,,,,,,,,,,,,,
placement.count=0
primaryTheme=STONE_WOOD
skyboxPath=
spawnX=1
spawnY=1
themes.0=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.1=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.10=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.11=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.2=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.3=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.4=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.5=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.6=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.7=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.8=0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.9=0,0,0,0,0,0,0,0,0,0,0,0,0,0
tiles.0=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL
tiles.1=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.10=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.11=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL
tiles.2=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.3=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.4=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.5=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.6=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.7=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.8=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.9=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
trigger.count=0
width=14
