#Aether map design
#Sat Jul 18 22:06:46 JST 2026
alternateTheme=STONE_WOOD
description=starting area tutorial\n07.14.2026
displayName=tutorial
geometry.height.0=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.1=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.10=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.11=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.12=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.13=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.14=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.15=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.16=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.17=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.18=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.2=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.3=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.4=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.5=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.6=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.7=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.8=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.9=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
height=19
musicPath=
paint.door.0=,,,,,,,,,,,,,,,,,,
paint.door.1=,,,,,,,,,,,,,,,,,,
paint.door.10=,,,,,,,,,,,,,,,,,,
paint.door.11=,,,,,,,,,,,,,,,,,,
paint.door.12=,,,,,,,,,,,,,,,,,,
paint.door.13=,,,,,,,,,,,,,,,,,,
paint.door.14=,,,,,,,,,,,,,,,,,,
paint.door.15=,,,,,,,,,,,,,,,,,,
paint.door.16=,,,,,,,,,,,,,,,,,,
paint.door.17=,,,,,,,,,,,,,,,,,,
paint.door.18=,,,,,,,,,,,,,,,,,,
paint.door.2=,,,,,,,,,,,,,,,,,,
paint.door.3=,,,,,,,,,,,,,,,,,,
paint.door.4=,,,,,,,,,,,,,,,,,,
paint.door.5=,,,,,,,,,,,,,,,,,,
paint.door.6=,,,,,,,,,,,,,,,,,,
paint.door.7=,,,,,,,,,,,,,,,,,,
paint.door.8=,,,,,,,,,,,,,,,,,,
paint.door.9=,,,,,,,,,,,,,,,,,,
paint.floor.0=,,,,,,,,,,,,,,,,,,
paint.floor.1=,,,,,,,,,,,,,,,,,,
paint.floor.10=,,,,,,,,,,,,,,,,,,
paint.floor.11=,,,,,,,,,,,,,,,,,,
paint.floor.12=,,,,,,,,,,,,,,,,,,
paint.floor.13=,,,,,,,,,,,,,,,,,,
paint.floor.14=,,,,,,,,,,,,,,,,,,
paint.floor.15=,,,,,,,,,,,,,,,,,,
paint.floor.16=,,,,,,,,,,,,,,,,,,
paint.floor.17=,,,,,,,,,,,,,,,,,,
paint.floor.18=,,,,,,,,,,,,,,,,,,
paint.floor.2=,,,,,,,,,,,,,,,,,,
paint.floor.3=,,,,,,,,,,,,,,,,,,
paint.floor.4=,,,,,,,,,,,,,,,,,,
paint.floor.5=,,,,,,,,,,,,,,,,,,
paint.floor.6=,,,,,,,,,,,,,,,,,,
paint.floor.7=,,,,,,,,,,,,,,,,,,
paint.floor.8=,,,,,,,,,,,,,,,,,,
paint.floor.9=,,,,,,,,,,,,,,,,,,
paint.roof.0=,,,,,,,,,,,,,,,,,,
paint.roof.1=,,,,,,,,,,,,,,,,,,
paint.roof.10=,,,,,,,,,,,,,,,,,,
paint.roof.11=,,,,,,,,,,,,,,,,,,
paint.roof.12=,,,,,,,,,,,,,,,,,,
paint.roof.13=,,,,,,,,,,,,,,,,,,
paint.roof.14=,,,,,,,,,,,,,,,,,,
paint.roof.15=,,,,,,,,,,,,,,,,,,
paint.roof.16=,,,,,,,,,,,,,,,,,,
paint.roof.17=,,,,,,,,,,,,,,,,,,
paint.roof.18=,,,,,,,,,,,,,,,,,,
paint.roof.2=,,,,,,,,,,,,,,,,,,
paint.roof.3=,,,,,,,,,,,,,,,,,,
paint.roof.4=,,,,,,,,,,,,,,,,,,
paint.roof.5=,,,,,,,,,,,,,,,,,,
paint.roof.6=,,,,,,,,,,,,,,,,,,
paint.roof.7=,,,,,,,,,,,,,,,,,,
paint.roof.8=,,,,,,,,,,,,,,,,,,
paint.roof.9=,,,,,,,,,,,,,,,,,,
paint.wall.0=,,,,,,,,,,,,,,,,,,
paint.wall.1=,,,,,,,,,,,,,,,,,,
paint.wall.10=,,,,,,,,,,,,,,,,,,
paint.wall.11=,,,,,,,,,,,,,,,,,,
paint.wall.12=,,,,,,,,,,,,,,,,,,
paint.wall.13=,,,,,,,,,,,,,,,,,,
paint.wall.14=,,,,,,,,,,,,,,,,,,
paint.wall.15=,,,,,,,,,,,,,,,,,,
paint.wall.16=,,,,,,,,,,,,,,,,,,
paint.wall.17=,,,,,,,,,,,,,,,,,,
paint.wall.18=,,,,,,,,,,,,,,,,,,
paint.wall.2=,,,,,,,,,,,,,,,,,,
paint.wall.3=,,,,,,,,,,,,,,,,,,
paint.wall.4=,,,,,,,,,,,,,,,,,,
paint.wall.5=,,,,,,,,,,,,,,,,,,
paint.wall.6=,,,,,,,,,,,,,,,,,,
paint.wall.7=,,,,,,,,,,,,,,,,,,
paint.wall.8=,,,,,,,,,,,,,,,,,,
paint.wall.9=,,,,,,,,,,,,,,,,,,
placement.0.id=authored_dialogue_new_npc
placement.0.kind=AUTHORED_DIALOGUE_NPC
placement.0.x=2
placement.0.y=9
placement.1.id=authored_dialogue_new_npc
placement.1.kind=AUTHORED_DIALOGUE_NPC
placement.1.x=2
placement.1.y=5
placement.10.id=custom_mob_kobold
placement.10.kind=ENEMY
placement.10.x=16
placement.10.y=10
placement.11.id=custom_mob_kobold
placement.11.kind=ENEMY
placement.11.x=16
placement.11.y=7
placement.12.id=custom_mob_kobold
placement.12.kind=ENEMY
placement.12.x=14
placement.12.y=4
placement.13.id=custom_mob_kobold
placement.13.kind=ENEMY
placement.13.x=10
placement.13.y=2
placement.14.id=authored_dialogue_new_npc
placement.14.kind=AUTHORED_DIALOGUE_NPC
placement.14.x=9
placement.14.y=9
placement.15.id=map_link|assets/editor/worlds/overworld/world.properties|5|6
placement.15.kind=INTERACTION
placement.15.x=13
placement.15.y=0
placement.2.id=CAMPFIRE
placement.2.kind=CRAFTING_NODE
placement.2.x=3
placement.2.y=5
placement.3.id=FISHING_SHOAL
placement.3.kind=GATHERING_NODE
placement.3.x=4
placement.3.y=1
placement.4.id=FISHING_SHOAL
placement.4.kind=GATHERING_NODE
placement.4.x=7
placement.4.y=1
placement.5.id=node_copper_rock
placement.5.kind=GATHERING_NODE
placement.5.x=1
placement.5.y=15
placement.6.id=node_copper_rock
placement.6.kind=GATHERING_NODE
placement.6.x=2
placement.6.y=16
placement.7.id=FURNACE
placement.7.kind=CRAFTING_NODE
placement.7.x=4
placement.7.y=8
placement.8.id=ANVIL
placement.8.kind=CRAFTING_NODE
placement.8.x=1
placement.8.y=11
placement.9.id=custom_mob_kobold
placement.9.kind=ENEMY
placement.9.x=15
placement.9.y=16
placement.count=16
primaryTheme=STONE_WOOD
skyboxPath=
spawnX=1
spawnY=1
themes.0=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.1=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.10=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.11=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.12=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.13=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.14=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.15=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.16=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.17=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.18=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.2=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.3=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.4=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.5=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.6=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.7=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.8=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.9=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
tiles.0=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,QUEST_DOOR_CLOSED,WALL,WALL,WALL,WALL,WALL
tiles.1=WALL,FLOOR,FLOOR,WALL,FLOOR,WATER,WATER,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.10=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.11=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.12=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.13=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.14=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.15=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,QUEST_DOOR_CLOSED,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.16=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.17=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.18=WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL
tiles.2=WALL,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.3=WALL,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.4=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.5=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.6=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.7=WALL,WALL,WALL,WALL,WALL,WALL,QUEST_DOOR_CLOSED,WALL,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.8=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
tiles.9=WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,WALL
trigger.0.action.0.targetX=6
trigger.0.action.0.targetY=7
trigger.0.action.0.type=CLOSE_DOOR
trigger.0.action.count=1
trigger.0.fireMode=ON_ENTRY
trigger.0.id=Tutorial-DoorTrigger-1
trigger.0.oneShot=true
trigger.0.requiredQuestId=
trigger.0.requiredQuestStage=0
trigger.0.x=6
trigger.0.y=9
trigger.1.action.0.targetX=6
trigger.1.action.0.targetY=7
trigger.1.action.0.type=CLOSE_DOOR
trigger.1.action.count=1
trigger.1.fireMode=ON_ENTRY
trigger.1.id=trigger_2
trigger.1.oneShot=true
trigger.1.requiredQuestId=
trigger.1.requiredQuestStage=0
trigger.1.x=5
trigger.1.y=8
trigger.2.action.0.targetX=6
trigger.2.action.0.targetY=7
trigger.2.action.0.type=CLOSE_DOOR
trigger.2.action.count=1
trigger.2.fireMode=ON_ENTRY
trigger.2.id=trigger_3
trigger.2.oneShot=true
trigger.2.requiredQuestId=
trigger.2.requiredQuestStage=0
trigger.2.x=7
trigger.2.y=8
trigger.3.action.0.targetX=8
trigger.3.action.0.targetY=15
trigger.3.action.0.type=CLOSE_DOOR
trigger.3.action.count=1
trigger.3.fireMode=ON_ENTRY
trigger.3.id=trigger_4
trigger.3.oneShot=true
trigger.3.requiredQuestId=
trigger.3.requiredQuestStage=0
trigger.3.x=10
trigger.3.y=15
trigger.4.action.0.targetX=8
trigger.4.action.0.targetY=15
trigger.4.action.0.type=CLOSE_DOOR
trigger.4.action.count=1
trigger.4.fireMode=ON_ENTRY
trigger.4.id=trigger_5
trigger.4.oneShot=true
trigger.4.requiredQuestId=
trigger.4.requiredQuestStage=0
trigger.4.x=9
trigger.4.y=14
trigger.5.action.0.targetX=8
trigger.5.action.0.targetY=15
trigger.5.action.0.type=CLOSE_DOOR
trigger.5.action.count=1
trigger.5.fireMode=ON_ENTRY
trigger.5.id=trigger_6
trigger.5.oneShot=true
trigger.5.requiredQuestId=
trigger.5.requiredQuestStage=0
trigger.5.x=9
trigger.5.y=16
trigger.6.action.0.targetX=6
trigger.6.action.0.targetY=7
trigger.6.action.0.type=OPEN_DOOR
trigger.6.action.count=1
trigger.6.fireMode=ON_QUEST_STAGE
trigger.6.id=tutorial_unlock_mining_area
trigger.6.oneShot=true
trigger.6.requiredQuestId=authored_quest_a_warrior_s_guidance
trigger.6.requiredQuestStage=3
trigger.6.x=6
trigger.6.y=7
trigger.7.action.0.targetX=8
trigger.7.action.0.targetY=15
trigger.7.action.0.type=OPEN_DOOR
trigger.7.action.count=1
trigger.7.fireMode=ON_QUEST_STAGE
trigger.7.id=tutorial_unlock_combat_area
trigger.7.oneShot=true
trigger.7.requiredQuestId=authored_quest_a_warrior_s_guidance
trigger.7.requiredQuestStage=6
trigger.7.x=8
trigger.7.y=15
trigger.count=8
width=19
