#Aether open world manifest
#Wed Aug 12 06:32:49 JST 2026
chunk.0.path=chunks/-2_-3.properties
chunk.0.x=-2
chunk.0.y=-3
chunk.1.path=chunks/-1_-3.properties
chunk.1.x=-1
chunk.1.y=-3
chunk.10.path=chunks/-2_0.properties
chunk.10.x=-2
chunk.10.y=0
chunk.11.path=chunks/-1_0.properties
chunk.11.x=-1
chunk.11.y=0
chunk.12.path=chunks/0_0.properties
chunk.12.x=0
chunk.12.y=0
chunk.13.path=chunks/1_0.properties
chunk.13.x=1
chunk.13.y=0
chunk.14.path=chunks/-1_1.properties
chunk.14.x=-1
chunk.14.y=1
chunk.15.path=chunks/0_1.properties
chunk.15.x=0
chunk.15.y=1
chunk.16.path=chunks/1_1.properties
chunk.16.x=1
chunk.16.y=1
chunk.2.path=chunks/0_-3.properties
chunk.2.x=0
chunk.2.y=-3
chunk.3.path=chunks/-2_-2.properties
chunk.3.x=-2
chunk.3.y=-2
chunk.4.path=chunks/-1_-2.properties
chunk.4.x=-1
chunk.4.y=-2
chunk.5.path=chunks/0_-2.properties
chunk.5.x=0
chunk.5.y=-2
chunk.6.path=chunks/-2_-1.properties
chunk.6.x=-2
chunk.6.y=-1
chunk.7.path=chunks/-1_-1.properties
chunk.7.x=-1
chunk.7.y=-1
chunk.8.path=chunks/0_-1.properties
chunk.8.x=0
chunk.8.y=-1
chunk.9.path=chunks/1_-1.properties
chunk.9.x=1
chunk.9.y=-1
chunk.count=17
chunkHeight=32
chunkWidth=32
description=
displayName=Overworld
formatVersion=1
startX=14
startY=13
type=open-world
worldId=overworld
