#Aether open world manifest
#Sat Jul 18 17:46:56 JST 2026
chunk.0.path=chunks/0_0.properties
chunk.0.x=0
chunk.0.y=0
chunk.count=1
chunkHeight=32
chunkWidth=32
description=
displayName=Overworld
formatVersion=1
startX=1
startY=1
type=open-world
worldId=overworld
