#Aether open world manifest
#Sun Jul 19 09:57:01 JST 2026
chunk.0.path=chunks/-1_-1.properties
chunk.0.x=-1
chunk.0.y=-1
chunk.1.path=chunks/0_-1.properties
chunk.1.x=0
chunk.1.y=-1
chunk.2.path=chunks/1_-1.properties
chunk.2.x=1
chunk.2.y=-1
chunk.3.path=chunks/-1_0.properties
chunk.3.x=-1
chunk.3.y=0
chunk.4.path=chunks/0_0.properties
chunk.4.x=0
chunk.4.y=0
chunk.5.path=chunks/1_0.properties
chunk.5.x=1
chunk.5.y=0
chunk.6.path=chunks/-1_1.properties
chunk.6.x=-1
chunk.6.y=1
chunk.7.path=chunks/0_1.properties
chunk.7.x=0
chunk.7.y=1
chunk.8.path=chunks/1_1.properties
chunk.8.x=1
chunk.8.y=1
chunk.count=9
chunkHeight=32
chunkWidth=32
description=
displayName=Overworld
formatVersion=1
startX=44
startY=6
type=open-world
worldId=overworld
