#Aether map design
#Sun Jul 19 09:37:27 JST 2026
alternateTheme=OUTDOOR_HOUSE_GRASS
description=
displayName=Overworld (-1,1)
geometry.height.0=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.1=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.10=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.11=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.12=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.13=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.14=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.15=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.16=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.17=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.18=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.19=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.2=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.20=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.21=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.22=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.23=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.24=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.25=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.26=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.27=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.28=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.29=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.3=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.30=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.31=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.4=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.5=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.6=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.7=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.8=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
geometry.height.9=1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
height=32
mobArea.0=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.1=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.10=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.11=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.12=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.13=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.14=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.15=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.16=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.17=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.18=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.19=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.2=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.20=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.21=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.22=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.23=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.24=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.25=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.26=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.27=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.28=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.29=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.3=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.30=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.31=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.4=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.5=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.6=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.7=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.8=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
mobArea.9=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
musicPath=
paint.door.0=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.1=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.10=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.11=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.12=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.13=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.14=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.15=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.16=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.17=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.18=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.19=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.2=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.20=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.21=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.22=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.23=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.24=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.25=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.26=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.27=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.28=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.29=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.3=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.30=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.31=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.4=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.5=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.6=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.7=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.8=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.door.9=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.0=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.1=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.10=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.11=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.12=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.13=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.14=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.15=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.16=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.17=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.18=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.19=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.2=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.20=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.21=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.22=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.23=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.24=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.25=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.26=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.27=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.28=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.29=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.3=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.30=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.31=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.4=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.5=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.6=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.7=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.8=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.floor.9=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.0=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.1=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.10=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.11=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.12=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.13=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.14=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.15=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.16=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.17=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.18=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.19=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.2=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.20=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.21=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.22=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.23=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.24=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.25=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.26=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.27=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.28=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.29=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.3=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.30=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.31=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.4=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.5=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.6=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.7=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.8=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.roof.9=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.0=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.1=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.10=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.11=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.12=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.13=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.14=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.15=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.16=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.17=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.18=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.19=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.2=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.20=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.21=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.22=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.23=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.24=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.25=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.26=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.27=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.28=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.29=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.3=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.30=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.31=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.4=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.5=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.6=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.7=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.8=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
paint.wall.9=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
placement.count=0
primaryTheme=OUTDOOR_HOUSE_GRASS
skyboxPath=assets/images/battle_backgrounds/Willibab's Pixel Battle Backgrounds/Daylight Box_0.png
spawnX=1
spawnY=1
themes.0=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.1=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.10=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.11=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.12=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.13=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.14=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.15=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.16=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.17=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.18=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.19=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.2=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.20=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.21=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.22=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.23=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.24=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.25=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.26=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.27=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.28=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.29=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.3=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.30=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.31=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.4=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.5=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.6=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.7=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.8=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
themes.9=0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
tiles.0=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.1=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.10=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.11=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.12=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.13=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.14=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.15=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.16=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.17=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.18=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.19=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.2=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.20=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.21=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.22=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.23=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.24=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.25=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.26=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.27=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.28=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.29=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.3=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.30=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.31=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.4=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.5=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.6=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.7=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.8=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
tiles.9=FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR,FLOOR
trigger.count=0
width=32
