#Aether map design
#Mon Jul 20 19:08:41 JST 2026
craftingRecipe.0.category=METAL
craftingRecipe.0.consumePrimary=true
craftingRecipe.0.consumeSecondary=true
craftingRecipe.0.displayName=Steel Recipe
craftingRecipe.0.outputItemId=custom_item_coal_iron_mix
craftingRecipe.0.outputStationType=
craftingRecipe.0.outputType=ITEM
craftingRecipe.0.primaryItemId=custom_item_coal
craftingRecipe.0.primaryQuantity=1
craftingRecipe.0.recipeId=recipe_steel_recipe
craftingRecipe.0.requiredLevel=27
craftingRecipe.0.requiredSkill=SMITHING
craftingRecipe.0.secondaryItemId=custom_item_iron_ore
craftingRecipe.0.secondaryQuantity=1
craftingRecipe.0.smeltOutputItemId=custom_item_steel_bar
craftingRecipe.0.smeltRequiredLevel=30
craftingRecipe.0.smeltXpReward=13
craftingRecipe.0.stationLifetimeMs=0
craftingRecipe.0.xpReward=4
craftingRecipe.1.category=METAL
craftingRecipe.1.consumePrimary=true
craftingRecipe.1.consumeSecondary=true
craftingRecipe.1.displayName=Bronze_Recipe
craftingRecipe.1.outputItemId=custom_item_tin_copper_mix
craftingRecipe.1.outputStationType=
craftingRecipe.1.outputType=ITEM
craftingRecipe.1.primaryItemId=COPPER_ORE
craftingRecipe.1.primaryQuantity=1
craftingRecipe.1.recipeId=recipe_bronze_recipe
craftingRecipe.1.requiredLevel=7
craftingRecipe.1.requiredSkill=SMITHING
craftingRecipe.1.secondaryItemId=custom_item_tin_ore
craftingRecipe.1.secondaryQuantity=1
craftingRecipe.1.smeltOutputItemId=custom_item_bronze_bar
craftingRecipe.1.smeltRequiredLevel=10
craftingRecipe.1.smeltXpReward=12
craftingRecipe.1.stationLifetimeMs=0
craftingRecipe.1.xpReward=3
craftingRecipe.count=2
