#Aether map design
#Wed Aug 12 07:42:17 JST 2026
craftingRecipe.schemaVersion=2
craftingRecipe.0.category=METAL
craftingRecipe.0.consumePrimary=true
craftingRecipe.0.consumeSecondary=true
craftingRecipe.0.displayName=Steel Recipe
craftingRecipe.0.outputItemId=custom_item_coal_iron_mix
craftingRecipe.0.outputStationType=
craftingRecipe.0.outputType=ITEM
craftingRecipe.0.primaryItemId=custom_item_coal
craftingRecipe.0.primaryQuantity=1
craftingRecipe.0.recipeId=recipe_steel_recipe
craftingRecipe.0.requiredLevel=27
craftingRecipe.0.requiredSkill=SMITHING
craftingRecipe.0.secondaryItemId=custom_item_iron_ore
craftingRecipe.0.secondaryQuantity=1
craftingRecipe.0.smeltOutputItemId=custom_item_steel_bar
craftingRecipe.0.smeltRequiredLevel=30
craftingRecipe.0.smeltXpReward=13
craftingRecipe.0.stationLifetimeMs=0
craftingRecipe.0.xpReward=4
craftingRecipe.1.category=METAL
craftingRecipe.1.consumePrimary=true
craftingRecipe.1.consumeSecondary=true
craftingRecipe.1.displayName=Bronze_Recipe
craftingRecipe.1.outputItemId=custom_item_tin_copper_mix
craftingRecipe.1.outputStationType=
craftingRecipe.1.outputType=ITEM
craftingRecipe.1.primaryItemId=COPPER_ORE
craftingRecipe.1.primaryQuantity=1
craftingRecipe.1.recipeId=recipe_bronze_recipe
craftingRecipe.1.requiredLevel=7
craftingRecipe.1.requiredSkill=SMITHING
craftingRecipe.1.secondaryItemId=custom_item_tin_ore
craftingRecipe.1.secondaryQuantity=1
craftingRecipe.1.smeltOutputItemId=custom_item_bronze_bar
craftingRecipe.1.smeltRequiredLevel=10
craftingRecipe.1.smeltXpReward=12
craftingRecipe.1.stationLifetimeMs=0
craftingRecipe.1.xpReward=3
craftingRecipe.2.category=MATERIAL
craftingRecipe.2.consumePrimary=true
craftingRecipe.2.consumeSecondary=false
craftingRecipe.2.displayName=Oak Wand Blank
craftingRecipe.2.outputItemId=custom_item_oak_wand_blank
craftingRecipe.2.outputStationType=
craftingRecipe.2.outputType=ITEM
craftingRecipe.2.primaryItemId=custom_item_oak_log
craftingRecipe.2.primaryQuantity=1
craftingRecipe.2.recipeId=recipe_carve_oak_wand_blank
craftingRecipe.2.requiredToolWeaponType=DAGGER
craftingRecipe.2.requiredLevel=1
craftingRecipe.2.requiredSkill=CRAFTING
craftingRecipe.2.secondaryItemId=
craftingRecipe.2.secondaryQuantity=0
craftingRecipe.2.smeltOutputItemId=
craftingRecipe.2.smeltRequiredLevel=1
craftingRecipe.2.smeltXpReward=0
craftingRecipe.2.stationLifetimeMs=0
craftingRecipe.2.xpReward=5
craftingRecipe.3.category=MATERIAL
craftingRecipe.3.consumePrimary=true
craftingRecipe.3.consumeSecondary=false
craftingRecipe.3.displayName=Oak Staff Shaft
craftingRecipe.3.outputItemId=custom_item_oak_staff_shaft
craftingRecipe.3.outputType=ITEM
craftingRecipe.3.primaryItemId=custom_item_oak_log
craftingRecipe.3.primaryQuantity=2
craftingRecipe.3.recipeId=recipe_carve_oak_staff_shaft
craftingRecipe.3.requiredLevel=1
craftingRecipe.3.requiredSkill=CRAFTING
craftingRecipe.3.requiredToolWeaponType=DAGGER
craftingRecipe.3.secondaryItemId=
craftingRecipe.3.secondaryQuantity=0
craftingRecipe.3.xpReward=10
craftingRecipe.4.category=WEAPON
craftingRecipe.4.consumePrimary=true
craftingRecipe.4.consumeSecondary=true
craftingRecipe.4.displayName=Oak Wand
craftingRecipe.4.outputItemId=custom_item_oak_wand
craftingRecipe.4.outputType=ITEM
craftingRecipe.4.primaryItemId=custom_item_oak_wand_blank
craftingRecipe.4.primaryQuantity=1
craftingRecipe.4.recipeId=recipe_oak_wand
craftingRecipe.4.requiredLevel=1
craftingRecipe.4.requiredSkill=CRAFTING
craftingRecipe.4.secondaryItemId=custom_item_inert_stone
craftingRecipe.4.secondaryQuantity=1
craftingRecipe.4.xpReward=10
craftingRecipe.5.category=WEAPON
craftingRecipe.5.consumePrimary=true
craftingRecipe.5.consumeSecondary=true
craftingRecipe.5.displayName=Oak Staff
craftingRecipe.5.outputItemId=custom_item_oak_staff
craftingRecipe.5.outputType=ITEM
craftingRecipe.5.primaryItemId=custom_item_oak_staff_shaft
craftingRecipe.5.primaryQuantity=1
craftingRecipe.5.recipeId=recipe_oak_staff
craftingRecipe.5.requiredLevel=1
craftingRecipe.5.requiredSkill=CRAFTING
craftingRecipe.5.secondaryItemId=custom_item_inert_stone
craftingRecipe.5.secondaryQuantity=1
craftingRecipe.5.xpReward=10
craftingRecipe.6.category=WEAPON
craftingRecipe.6.consumePrimary=true
craftingRecipe.6.consumeSecondary=true
craftingRecipe.6.displayName=Oak Fire Wand
craftingRecipe.6.outputItemId=custom_item_oak_fire_wand
craftingRecipe.6.outputType=ITEM
craftingRecipe.6.primaryItemId=custom_item_oak_wand_blank
craftingRecipe.6.primaryQuantity=1
craftingRecipe.6.recipeId=recipe_oak_fire_wand
craftingRecipe.6.requiredLevel=10
craftingRecipe.6.requiredSkill=CRAFTING
craftingRecipe.6.secondaryItemId=custom_item_fire_stone
craftingRecipe.6.secondaryQuantity=1
craftingRecipe.6.xpReward=10
craftingRecipe.7.category=WEAPON
craftingRecipe.7.consumePrimary=true
craftingRecipe.7.consumeSecondary=true
craftingRecipe.7.displayName=Oak Fire Staff
craftingRecipe.7.outputItemId=custom_item_oak_fire_staff
craftingRecipe.7.outputType=ITEM
craftingRecipe.7.primaryItemId=custom_item_oak_staff_shaft
craftingRecipe.7.primaryQuantity=1
craftingRecipe.7.recipeId=recipe_oak_fire_staff
craftingRecipe.7.requiredLevel=10
craftingRecipe.7.requiredSkill=CRAFTING
craftingRecipe.7.secondaryItemId=custom_item_fire_stone
craftingRecipe.7.secondaryQuantity=1
craftingRecipe.7.xpReward=10
craftingRecipe.8.category=WEAPON
craftingRecipe.8.consumePrimary=true
craftingRecipe.8.consumeSecondary=true
craftingRecipe.8.displayName=Oak Frost Wand
craftingRecipe.8.outputItemId=custom_item_oak_frost_wand
craftingRecipe.8.outputType=ITEM
craftingRecipe.8.primaryItemId=custom_item_oak_wand_blank
craftingRecipe.8.primaryQuantity=1
craftingRecipe.8.recipeId=recipe_oak_frost_wand
craftingRecipe.8.requiredLevel=20
craftingRecipe.8.requiredSkill=CRAFTING
craftingRecipe.8.secondaryItemId=custom_item_frost_stone
craftingRecipe.8.secondaryQuantity=1
craftingRecipe.8.xpReward=20
craftingRecipe.9.category=WEAPON
craftingRecipe.9.consumePrimary=true
craftingRecipe.9.consumeSecondary=true
craftingRecipe.9.displayName=Oak Frost Staff
craftingRecipe.9.outputItemId=custom_item_oak_frost_staff
craftingRecipe.9.outputType=ITEM
craftingRecipe.9.primaryItemId=custom_item_oak_staff_shaft
craftingRecipe.9.primaryQuantity=1
craftingRecipe.9.recipeId=recipe_oak_frost_staff
craftingRecipe.9.requiredLevel=20
craftingRecipe.9.requiredSkill=CRAFTING
craftingRecipe.9.secondaryItemId=custom_item_frost_stone
craftingRecipe.9.secondaryQuantity=1
craftingRecipe.9.xpReward=20
craftingRecipe.10.category=WEAPON
craftingRecipe.10.consumePrimary=true
craftingRecipe.10.consumeSecondary=true
craftingRecipe.10.displayName=Oak Storm Wand
craftingRecipe.10.outputItemId=custom_item_oak_storm_wand
craftingRecipe.10.outputType=ITEM
craftingRecipe.10.primaryItemId=custom_item_oak_wand_blank
craftingRecipe.10.primaryQuantity=1
craftingRecipe.10.recipeId=recipe_oak_storm_wand
craftingRecipe.10.requiredLevel=30
craftingRecipe.10.requiredSkill=CRAFTING
craftingRecipe.10.secondaryItemId=custom_item_storm_stone
craftingRecipe.10.secondaryQuantity=1
craftingRecipe.10.xpReward=30
craftingRecipe.11.category=WEAPON
craftingRecipe.11.consumePrimary=true
craftingRecipe.11.consumeSecondary=true
craftingRecipe.11.displayName=Oak Storm Staff
craftingRecipe.11.outputItemId=custom_item_oak_storm_staff
craftingRecipe.11.outputType=ITEM
craftingRecipe.11.primaryItemId=custom_item_oak_staff_shaft
craftingRecipe.11.primaryQuantity=1
craftingRecipe.11.recipeId=recipe_oak_storm_staff
craftingRecipe.11.requiredLevel=30
craftingRecipe.11.requiredSkill=CRAFTING
craftingRecipe.11.secondaryItemId=custom_item_storm_stone
craftingRecipe.11.secondaryQuantity=1
craftingRecipe.11.xpReward=30
craftingRecipe.12.category=WEAPON
craftingRecipe.12.consumePrimary=true
craftingRecipe.12.consumeSecondary=true
craftingRecipe.12.displayName=Oak Earth Wand
craftingRecipe.12.outputItemId=custom_item_oak_earth_wand
craftingRecipe.12.outputType=ITEM
craftingRecipe.12.primaryItemId=custom_item_oak_wand_blank
craftingRecipe.12.primaryQuantity=1
craftingRecipe.12.recipeId=recipe_oak_earth_wand
craftingRecipe.12.requiredLevel=40
craftingRecipe.12.requiredSkill=CRAFTING
craftingRecipe.12.secondaryItemId=custom_item_earth_stone
craftingRecipe.12.secondaryQuantity=1
craftingRecipe.12.xpReward=40
craftingRecipe.13.category=WEAPON
craftingRecipe.13.consumePrimary=true
craftingRecipe.13.consumeSecondary=true
craftingRecipe.13.displayName=Oak Earth Staff
craftingRecipe.13.outputItemId=custom_item_oak_earth_staff
craftingRecipe.13.outputType=ITEM
craftingRecipe.13.primaryItemId=custom_item_oak_staff_shaft
craftingRecipe.13.primaryQuantity=1
craftingRecipe.13.recipeId=recipe_oak_earth_staff
craftingRecipe.13.requiredLevel=40
craftingRecipe.13.requiredSkill=CRAFTING
craftingRecipe.13.secondaryItemId=custom_item_earth_stone
craftingRecipe.13.secondaryQuantity=1
craftingRecipe.13.xpReward=40
craftingRecipe.count=14
