#Aether map design
#Wed Aug 12 07:42:17 JST 2026
dialogue.0.bodyText=Hello again.\n- What is around here? \=> goodbye
dialogue.0.choice.count=0
dialogue.0.firstTalkNodeId=firstTalk
dialogue.0.followUpInteractionId=
dialogue.0.interactionId=authored_dialogue_villager
dialogue.0.node.0.bodyText=Did I just see you step out of the catacombs? Those should have been sealed... You don't seem like the mindless wandering outside. Either way, you will seldom find any hospitality around here, but you do look lost. Are you looking for something?
dialogue.0.node.0.canvasX=80
dialogue.0.node.0.canvasY=80
dialogue.0.node.0.choice.0.bodyText=
dialogue.0.node.0.choice.0.choiceId=dialogue_0_node_0_choice_0_choice
dialogue.0.node.0.choice.0.firstTalkOnly=false
dialogue.0.node.0.choice.0.label=Where am I?
dialogue.0.node.0.choice.0.requiredItemName=
dialogue.0.node.0.choice.0.reward.count=0
dialogue.0.node.0.choice.0.takeItemAmount=0
dialogue.0.node.0.choice.0.takeItemName=
dialogue.0.node.0.choice.0.targetNodeId=where_am_i
dialogue.0.node.0.choice.count=1
dialogue.0.node.0.nodeId=firstTalk
dialogue.0.node.1.bodyText=You are in a village. Probably the safest one you will find for some time.
dialogue.0.node.1.canvasX=340
dialogue.0.node.1.canvasY=80
dialogue.0.node.1.choice.count=0
dialogue.0.node.1.nodeId=where_am_i
dialogue.0.node.count=2
dialogue.0.repeatTalkNodeId=firstTalk
dialogue.0.reward.count=0
dialogue.0.speakerName=Villager
dialogue.0.visualPath=assets/images/monster/Nov-2015/mon/goblin.png
dialogue.count=1
dialogue.schemaVersion=3
