#Aether first-person viewmodel catalog
#Wed Aug 12 07:42:17 JST 2026
animationSet.0.binding.ATTACK_LEFT.camera.positionX=-0.2
animationSet.0.binding.ATTACK_LEFT.camera.positionY=-0.4
animationSet.0.binding.ATTACK_LEFT.camera.positionZ=-0.3
animationSet.0.binding.ATTACK_LEFT.camera.rotationX=0
animationSet.0.binding.ATTACK_LEFT.camera.rotationY=0
animationSet.0.binding.ATTACK_LEFT.camera.rotationZ=0
animationSet.0.binding.ATTACK_LEFT.clipName=FP_Slash
animationSet.0.binding.ATTACK_LEFT.impactFraction=0.55
animationSet.0.binding.ATTACK_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.0.binding.ATTACK_LEFT.speed=1
animationSet.0.binding.ATTACK_RIGHT.camera.positionX=-0.2
animationSet.0.binding.ATTACK_RIGHT.camera.positionY=-0.4
animationSet.0.binding.ATTACK_RIGHT.camera.positionZ=-0.3
animationSet.0.binding.ATTACK_RIGHT.camera.rotationX=0
animationSet.0.binding.ATTACK_RIGHT.camera.rotationY=0
animationSet.0.binding.ATTACK_RIGHT.camera.rotationZ=0
animationSet.0.binding.ATTACK_RIGHT.clipName=FP_Slash
animationSet.0.binding.ATTACK_RIGHT.impactFraction=0.55
animationSet.0.binding.ATTACK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.0.binding.ATTACK_RIGHT.speed=1
animationSet.0.binding.IDLE_LEFT.camera.positionX=0
animationSet.0.binding.IDLE_LEFT.camera.positionY=0
animationSet.0.binding.IDLE_LEFT.camera.positionZ=0
animationSet.0.binding.IDLE_LEFT.camera.rotationX=0
animationSet.0.binding.IDLE_LEFT.camera.rotationY=0
animationSet.0.binding.IDLE_LEFT.camera.rotationZ=0
animationSet.0.binding.IDLE_LEFT.clipName=FP_Rest
animationSet.0.binding.IDLE_LEFT.impactFraction=0.55
animationSet.0.binding.IDLE_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.0.binding.IDLE_LEFT.speed=1
animationSet.0.binding.IDLE_RIGHT.camera.positionX=0
animationSet.0.binding.IDLE_RIGHT.camera.positionY=0
animationSet.0.binding.IDLE_RIGHT.camera.positionZ=0
animationSet.0.binding.IDLE_RIGHT.camera.rotationX=0
animationSet.0.binding.IDLE_RIGHT.camera.rotationY=0
animationSet.0.binding.IDLE_RIGHT.camera.rotationZ=0
animationSet.0.binding.IDLE_RIGHT.clipName=FP_Rest
animationSet.0.binding.IDLE_RIGHT.impactFraction=0.55
animationSet.0.binding.IDLE_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.0.binding.IDLE_RIGHT.speed=1
animationSet.0.displayName=Block Arms Dagger
animationSet.0.id=block_arms_dagger
animationSet.0.rigId=player_default
animationSet.1.binding.ATTACK_RIGHT.camera.positionX=0
animationSet.1.binding.ATTACK_RIGHT.camera.positionY=0
animationSet.1.binding.ATTACK_RIGHT.camera.positionZ=0
animationSet.1.binding.ATTACK_RIGHT.camera.rotationX=0
animationSet.1.binding.ATTACK_RIGHT.camera.rotationY=0
animationSet.1.binding.ATTACK_RIGHT.camera.rotationZ=0
animationSet.1.binding.ATTACK_RIGHT.clipName=FP_Slash
animationSet.1.binding.ATTACK_RIGHT.impactFraction=0.55
animationSet.1.binding.ATTACK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.1.binding.ATTACK_RIGHT.speed=1
animationSet.1.binding.IDLE_RIGHT.camera.positionX=0
animationSet.1.binding.IDLE_RIGHT.camera.positionY=0
animationSet.1.binding.IDLE_RIGHT.camera.positionZ=0
animationSet.1.binding.IDLE_RIGHT.camera.rotationX=0
animationSet.1.binding.IDLE_RIGHT.camera.rotationY=0
animationSet.1.binding.IDLE_RIGHT.camera.rotationZ=0
animationSet.1.binding.IDLE_RIGHT.clipName=FP_Rest
animationSet.1.binding.IDLE_RIGHT.impactFraction=0.55
animationSet.1.binding.IDLE_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.1.binding.IDLE_RIGHT.speed=1
animationSet.1.displayName=Unarmed
animationSet.1.id=unarmed
animationSet.1.rigId=player_default
animationSet.2.binding.ATTACK_RIGHT.camera.positionX=0
animationSet.2.binding.ATTACK_RIGHT.camera.positionY=0
animationSet.2.binding.ATTACK_RIGHT.camera.positionZ=0
animationSet.2.binding.ATTACK_RIGHT.camera.rotationX=0
animationSet.2.binding.ATTACK_RIGHT.camera.rotationY=0
animationSet.2.binding.ATTACK_RIGHT.camera.rotationZ=0
animationSet.2.binding.ATTACK_RIGHT.clipName=FP_Slash
animationSet.2.binding.ATTACK_RIGHT.impactFraction=0.55
animationSet.2.binding.ATTACK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.2.binding.ATTACK_RIGHT.speed=1
animationSet.2.binding.IDLE_LEFT.camera.positionX=0
animationSet.2.binding.IDLE_LEFT.camera.positionY=0
animationSet.2.binding.IDLE_LEFT.camera.positionZ=0
animationSet.2.binding.IDLE_LEFT.camera.rotationX=0
animationSet.2.binding.IDLE_LEFT.camera.rotationY=0
animationSet.2.binding.IDLE_LEFT.camera.rotationZ=0
animationSet.2.binding.IDLE_LEFT.clipName=FP_Rest
animationSet.2.binding.IDLE_LEFT.impactFraction=0.55
animationSet.2.binding.IDLE_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.2.binding.IDLE_LEFT.speed=1
animationSet.2.binding.IDLE_RIGHT.camera.positionX=0
animationSet.2.binding.IDLE_RIGHT.camera.positionY=0
animationSet.2.binding.IDLE_RIGHT.camera.positionZ=0
animationSet.2.binding.IDLE_RIGHT.camera.rotationX=0
animationSet.2.binding.IDLE_RIGHT.camera.rotationY=0
animationSet.2.binding.IDLE_RIGHT.camera.rotationZ=0
animationSet.2.binding.IDLE_RIGHT.clipName=FP_Rest
animationSet.2.binding.IDLE_RIGHT.impactFraction=0.55
animationSet.2.binding.IDLE_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.2.binding.IDLE_RIGHT.speed=1
animationSet.2.displayName=Staff
animationSet.2.id=staff
animationSet.2.rigId=player_default
animationSet.3.binding.ATTACK_RIGHT.camera.positionX=0
animationSet.3.binding.ATTACK_RIGHT.camera.positionY=0
animationSet.3.binding.ATTACK_RIGHT.camera.positionZ=0
animationSet.3.binding.ATTACK_RIGHT.camera.rotationX=0
animationSet.3.binding.ATTACK_RIGHT.camera.rotationY=0
animationSet.3.binding.ATTACK_RIGHT.camera.rotationZ=0
animationSet.3.binding.ATTACK_RIGHT.clipName=FP_Slash
animationSet.3.binding.ATTACK_RIGHT.impactFraction=0.6
animationSet.3.binding.ATTACK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.3.binding.ATTACK_RIGHT.speed=0.8
animationSet.3.binding.IDLE_LEFT.camera.positionX=0
animationSet.3.binding.IDLE_LEFT.camera.positionY=0
animationSet.3.binding.IDLE_LEFT.camera.positionZ=0
animationSet.3.binding.IDLE_LEFT.camera.rotationX=0
animationSet.3.binding.IDLE_LEFT.camera.rotationY=0
animationSet.3.binding.IDLE_LEFT.camera.rotationZ=0
animationSet.3.binding.IDLE_LEFT.clipName=FP_Rest
animationSet.3.binding.IDLE_LEFT.impactFraction=0.55
animationSet.3.binding.IDLE_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.3.binding.IDLE_LEFT.speed=1
animationSet.3.binding.IDLE_RIGHT.camera.positionX=0
animationSet.3.binding.IDLE_RIGHT.camera.positionY=0
animationSet.3.binding.IDLE_RIGHT.camera.positionZ=0
animationSet.3.binding.IDLE_RIGHT.camera.rotationX=0
animationSet.3.binding.IDLE_RIGHT.camera.rotationY=0
animationSet.3.binding.IDLE_RIGHT.camera.rotationZ=0
animationSet.3.binding.IDLE_RIGHT.clipName=FP_Rest
animationSet.3.binding.IDLE_RIGHT.impactFraction=0.55
animationSet.3.binding.IDLE_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.3.binding.IDLE_RIGHT.speed=1
animationSet.3.displayName=Greatsword
animationSet.3.id=greatsword
animationSet.3.rigId=player_default
animationSet.4.binding.ATTACK_RIGHT.camera.positionX=0
animationSet.4.binding.ATTACK_RIGHT.camera.positionY=0
animationSet.4.binding.ATTACK_RIGHT.camera.positionZ=0
animationSet.4.binding.ATTACK_RIGHT.camera.rotationX=0
animationSet.4.binding.ATTACK_RIGHT.camera.rotationY=0
animationSet.4.binding.ATTACK_RIGHT.camera.rotationZ=0
animationSet.4.binding.ATTACK_RIGHT.clipName=FP_Slash
animationSet.4.binding.ATTACK_RIGHT.impactFraction=0.6
animationSet.4.binding.ATTACK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.4.binding.ATTACK_RIGHT.speed=0.6
animationSet.4.binding.BLOCK_LEFT.camera.positionX=0
animationSet.4.binding.BLOCK_LEFT.camera.positionY=0
animationSet.4.binding.BLOCK_LEFT.camera.positionZ=0
animationSet.4.binding.BLOCK_LEFT.camera.rotationX=0
animationSet.4.binding.BLOCK_LEFT.camera.rotationY=0
animationSet.4.binding.BLOCK_LEFT.camera.rotationZ=0
animationSet.4.binding.BLOCK_LEFT.clipName=FP_Block
animationSet.4.binding.BLOCK_LEFT.impactFraction=0.55
animationSet.4.binding.BLOCK_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.4.binding.BLOCK_LEFT.speed=1
animationSet.4.binding.IDLE_LEFT.camera.positionX=0
animationSet.4.binding.IDLE_LEFT.camera.positionY=0
animationSet.4.binding.IDLE_LEFT.camera.positionZ=0
animationSet.4.binding.IDLE_LEFT.camera.rotationX=0
animationSet.4.binding.IDLE_LEFT.camera.rotationY=0
animationSet.4.binding.IDLE_LEFT.camera.rotationZ=0
animationSet.4.binding.IDLE_LEFT.clipName=FP_Rest
animationSet.4.binding.IDLE_LEFT.impactFraction=0.55
animationSet.4.binding.IDLE_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.4.binding.IDLE_LEFT.speed=1
animationSet.4.binding.IDLE_RIGHT.camera.positionX=0
animationSet.4.binding.IDLE_RIGHT.camera.positionY=0
animationSet.4.binding.IDLE_RIGHT.camera.positionZ=0
animationSet.4.binding.IDLE_RIGHT.camera.rotationX=0
animationSet.4.binding.IDLE_RIGHT.camera.rotationY=0
animationSet.4.binding.IDLE_RIGHT.camera.rotationZ=0
animationSet.4.binding.IDLE_RIGHT.clipName=FP_Rest
animationSet.4.binding.IDLE_RIGHT.impactFraction=0.55
animationSet.4.binding.IDLE_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.4.binding.IDLE_RIGHT.speed=1
animationSet.4.displayName=Dagger
animationSet.4.id=dagger
animationSet.4.rigId=player_default
animationSet.5.binding.ATTACK_RIGHT.camera.positionX=0
animationSet.5.binding.ATTACK_RIGHT.camera.positionY=0
animationSet.5.binding.ATTACK_RIGHT.camera.positionZ=0
animationSet.5.binding.ATTACK_RIGHT.camera.rotationX=0
animationSet.5.binding.ATTACK_RIGHT.camera.rotationY=0
animationSet.5.binding.ATTACK_RIGHT.camera.rotationZ=0
animationSet.5.binding.ATTACK_RIGHT.clipName=FP_Slash
animationSet.5.binding.ATTACK_RIGHT.impactFraction=0.55
animationSet.5.binding.ATTACK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.5.binding.ATTACK_RIGHT.speed=0.5
animationSet.5.binding.BLOCK_LEFT.camera.positionX=0
animationSet.5.binding.BLOCK_LEFT.camera.positionY=0
animationSet.5.binding.BLOCK_LEFT.camera.positionZ=0
animationSet.5.binding.BLOCK_LEFT.camera.rotationX=0
animationSet.5.binding.BLOCK_LEFT.camera.rotationY=0
animationSet.5.binding.BLOCK_LEFT.camera.rotationZ=0
animationSet.5.binding.BLOCK_LEFT.clipName=FP_Block
animationSet.5.binding.BLOCK_LEFT.impactFraction=0.55
animationSet.5.binding.BLOCK_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.5.binding.BLOCK_LEFT.speed=1
animationSet.5.binding.IDLE_LEFT.camera.positionX=0
animationSet.5.binding.IDLE_LEFT.camera.positionY=0
animationSet.5.binding.IDLE_LEFT.camera.positionZ=0
animationSet.5.binding.IDLE_LEFT.camera.rotationX=0
animationSet.5.binding.IDLE_LEFT.camera.rotationY=0
animationSet.5.binding.IDLE_LEFT.camera.rotationZ=0
animationSet.5.binding.IDLE_LEFT.clipName=FP_Rest
animationSet.5.binding.IDLE_LEFT.impactFraction=0.55
animationSet.5.binding.IDLE_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.5.binding.IDLE_LEFT.speed=1
animationSet.5.binding.IDLE_RIGHT.camera.positionX=0
animationSet.5.binding.IDLE_RIGHT.camera.positionY=0
animationSet.5.binding.IDLE_RIGHT.camera.positionZ=0
animationSet.5.binding.IDLE_RIGHT.camera.rotationX=0
animationSet.5.binding.IDLE_RIGHT.camera.rotationY=0
animationSet.5.binding.IDLE_RIGHT.camera.rotationZ=0
animationSet.5.binding.IDLE_RIGHT.clipName=FP_Rest
animationSet.5.binding.IDLE_RIGHT.impactFraction=0.55
animationSet.5.binding.IDLE_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.5.binding.IDLE_RIGHT.speed=1
animationSet.5.displayName=Mace
animationSet.5.id=mace
animationSet.5.rigId=player_default
animationSet.6.binding.ATTACK_RIGHT.camera.positionX=0
animationSet.6.binding.ATTACK_RIGHT.camera.positionY=0
animationSet.6.binding.ATTACK_RIGHT.camera.positionZ=0
animationSet.6.binding.ATTACK_RIGHT.camera.rotationX=0
animationSet.6.binding.ATTACK_RIGHT.camera.rotationY=0
animationSet.6.binding.ATTACK_RIGHT.camera.rotationZ=0
animationSet.6.binding.ATTACK_RIGHT.clipName=FP_Slash
animationSet.6.binding.ATTACK_RIGHT.impactFraction=0.55
animationSet.6.binding.ATTACK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.6.binding.ATTACK_RIGHT.speed=1
animationSet.6.binding.BLOCK_LEFT.camera.positionX=0
animationSet.6.binding.BLOCK_LEFT.camera.positionY=0
animationSet.6.binding.BLOCK_LEFT.camera.positionZ=0
animationSet.6.binding.BLOCK_LEFT.camera.rotationX=0
animationSet.6.binding.BLOCK_LEFT.camera.rotationY=0
animationSet.6.binding.BLOCK_LEFT.camera.rotationZ=0
animationSet.6.binding.BLOCK_LEFT.clipName=FP_Block
animationSet.6.binding.BLOCK_LEFT.impactFraction=0.55
animationSet.6.binding.BLOCK_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.6.binding.BLOCK_LEFT.speed=1
animationSet.6.binding.IDLE_LEFT.camera.positionX=0
animationSet.6.binding.IDLE_LEFT.camera.positionY=0
animationSet.6.binding.IDLE_LEFT.camera.positionZ=0
animationSet.6.binding.IDLE_LEFT.camera.rotationX=0
animationSet.6.binding.IDLE_LEFT.camera.rotationY=0
animationSet.6.binding.IDLE_LEFT.camera.rotationZ=0
animationSet.6.binding.IDLE_LEFT.clipName=FP_Rest
animationSet.6.binding.IDLE_LEFT.impactFraction=0.55
animationSet.6.binding.IDLE_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.6.binding.IDLE_LEFT.speed=1
animationSet.6.binding.IDLE_RIGHT.camera.positionX=0
animationSet.6.binding.IDLE_RIGHT.camera.positionY=0
animationSet.6.binding.IDLE_RIGHT.camera.positionZ=0
animationSet.6.binding.IDLE_RIGHT.camera.rotationX=0
animationSet.6.binding.IDLE_RIGHT.camera.rotationY=0
animationSet.6.binding.IDLE_RIGHT.camera.rotationZ=0
animationSet.6.binding.IDLE_RIGHT.clipName=FP_Rest
animationSet.6.binding.IDLE_RIGHT.impactFraction=0.55
animationSet.6.binding.IDLE_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
animationSet.6.binding.IDLE_RIGHT.speed=1
animationSet.6.displayName=Sword
animationSet.6.id=sword
animationSet.6.rigId=player_default
animationSet.count=7
defaultRigId=player_default
itemProfile.0.animationSetId=dagger
itemProfile.0.attachmentBone=
itemProfile.0.itemId=custom_item_copper_dagger_copy
itemProfile.0.leftArmorPath=
itemProfile.0.leftCoverage=OVERLAY
itemProfile.0.rigId=player_default
itemProfile.0.rightArmorPath=
itemProfile.0.rightCoverage=OVERLAY
itemProfile.0.secondaryGripX=0
itemProfile.0.secondaryGripY=0
itemProfile.0.secondaryGripZ=0
itemProfile.0.socket.positionX=-0.098469
itemProfile.0.socket.positionY=0.138382
itemProfile.0.socket.positionZ=-0.380919
itemProfile.0.socket.rotationX=234.441
itemProfile.0.socket.rotationY=79
itemProfile.0.socket.rotationZ=205.365
itemProfile.0.socket.scale=2.54
itemProfile.0.wieldHand=RIGHT
itemProfile.1.animationSetId=unarmed
itemProfile.1.attachmentBone=Hand.L
itemProfile.1.itemId=custom_item_copper_shield
itemProfile.1.leftArmorPath=
itemProfile.1.leftCoverage=OVERLAY
itemProfile.1.rigId=player_default
itemProfile.1.rightArmorPath=
itemProfile.1.rightCoverage=OVERLAY
itemProfile.1.secondaryGripX=0
itemProfile.1.secondaryGripY=0
itemProfile.1.secondaryGripZ=0
itemProfile.1.socket.positionX=-0.499747
itemProfile.1.socket.positionY=-0.630232
itemProfile.1.socket.positionZ=-0.24607
itemProfile.1.socket.rotationX=272
itemProfile.1.socket.rotationY=288
itemProfile.1.socket.rotationZ=264
itemProfile.1.socket.scale=1.39
itemProfile.1.wieldHand=LEFT
itemProfile.count=2
rig.0.cameraAnchorBone=Bone
rig.0.crossfadeMs=120
rig.0.displayName=Player Default
rig.0.fallback.BLOCK_LEFT.camera.positionX=0
rig.0.fallback.BLOCK_LEFT.camera.positionY=0
rig.0.fallback.BLOCK_LEFT.camera.positionZ=0
rig.0.fallback.BLOCK_LEFT.camera.rotationX=0
rig.0.fallback.BLOCK_LEFT.camera.rotationY=0
rig.0.fallback.BLOCK_LEFT.camera.rotationZ=0
rig.0.fallback.BLOCK_LEFT.clipName=FP_Block
rig.0.fallback.BLOCK_LEFT.impactFraction=0.5
rig.0.fallback.BLOCK_LEFT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.fallback.BLOCK_LEFT.speed=1
rig.0.fallback.BLOCK_RIGHT.camera.positionX=0
rig.0.fallback.BLOCK_RIGHT.camera.positionY=0
rig.0.fallback.BLOCK_RIGHT.camera.positionZ=0
rig.0.fallback.BLOCK_RIGHT.camera.rotationX=0
rig.0.fallback.BLOCK_RIGHT.camera.rotationY=0
rig.0.fallback.BLOCK_RIGHT.camera.rotationZ=0
rig.0.fallback.BLOCK_RIGHT.clipName=FP_Block
rig.0.fallback.BLOCK_RIGHT.impactFraction=0.5
rig.0.fallback.BLOCK_RIGHT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.fallback.BLOCK_RIGHT.speed=1
rig.0.fallback.CAST.camera.positionX=0
rig.0.fallback.CAST.camera.positionY=0
rig.0.fallback.CAST.camera.positionZ=0
rig.0.fallback.CAST.camera.rotationX=0
rig.0.fallback.CAST.camera.rotationY=0
rig.0.fallback.CAST.camera.rotationZ=0
rig.0.fallback.CAST.clipName=FP_Cast
rig.0.fallback.CAST.impactFraction=0.72
rig.0.fallback.CAST.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.fallback.CAST.speed=1
rig.0.fallback.DODGE.camera.positionX=0
rig.0.fallback.DODGE.camera.positionY=0
rig.0.fallback.DODGE.camera.positionZ=0
rig.0.fallback.DODGE.camera.rotationX=0
rig.0.fallback.DODGE.camera.rotationY=0
rig.0.fallback.DODGE.camera.rotationZ=0
rig.0.fallback.DODGE.clipName=FP_Dodge
rig.0.fallback.DODGE.impactFraction=0.45
rig.0.fallback.DODGE.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.fallback.DODGE.speed=1
rig.0.fallback.HIT.camera.positionX=0
rig.0.fallback.HIT.camera.positionY=0
rig.0.fallback.HIT.camera.positionZ=0
rig.0.fallback.HIT.camera.rotationX=0
rig.0.fallback.HIT.camera.rotationY=0
rig.0.fallback.HIT.camera.rotationZ=0
rig.0.fallback.HIT.clipName=FP_Hit
rig.0.fallback.HIT.impactFraction=0.25
rig.0.fallback.HIT.path=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.fallback.HIT.speed=1
rig.0.fieldOfViewDegrees=70
rig.0.id=player_default
rig.0.left.elbowBone=ForeArm.L
rig.0.left.handBone=Hand.L
rig.0.left.modelPath=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.left.shoulderBone=Shoulder.L
rig.0.left.visibleMeshes=FP_Arm_Left_Mesh;FP_Hand_Left_Mesh
rig.0.modelPath=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.nearPlane=0.05
rig.0.positionX=0
rig.0.positionY=-0.85
rig.0.positionZ=0.2
rig.0.right.elbowBone=ForeArm.R
rig.0.right.handBone=Hand.R
rig.0.right.modelPath=assets/3D/bodyparts/FP_Arms_Runtime.glb
rig.0.right.shoulderBone=Shoulder.R
rig.0.right.visibleMeshes=FP_Arm_Right_Mesh;FP_Hand_Right_Mesh
rig.0.rotationX=0
rig.0.rotationY=180
rig.0.rotationZ=0
rig.0.scale=1
rig.count=1
schemaVersion=3
weaponDefault.DAGGER=sword
weaponDefault.GREATSWORD=greatsword
weaponDefault.MACE=mace
weaponDefault.STAFF=staff
weaponDefault.SWORD=sword
