#Aether map design
#Mon Jul 20 19:08:41 JST 2026
gatheringNode.0.displayName=Iron Rock
gatheringNode.0.frame.0=assets/images/generic/rocks/B_Rock3_Node1.png
gatheringNode.0.frame.1=assets/images/generic/rocks/B_Rock3_Node2.png
gatheringNode.0.frame.2=assets/images/generic/rocks/B_Rock3_Node3.png
gatheringNode.0.frame.count=3
gatheringNode.0.frameDurationMs=1000
gatheringNode.0.gatherXpReward=35
gatheringNode.0.gatheringSkill=MINING
gatheringNode.0.loot.0.chance=1.0
gatheringNode.0.loot.0.itemId=custom_item_iron_ore
gatheringNode.0.loot.count=1
gatheringNode.0.nodeId=node_iron_rock
gatheringNode.0.nodeType=MINING_ROCK
gatheringNode.0.outputItemId=custom_item_iron_ore
gatheringNode.0.requiredLevel=20
gatheringNode.0.smeltOutputItemId=custom_item_iron_bar
gatheringNode.0.smeltRequiredLevel=15
gatheringNode.0.smeltXpReward=13
gatheringNode.0.visualScale=1.35
gatheringNode.1.displayName=Coal Rock
gatheringNode.1.frame.0=assets/images/generic/rocks/A_Rock2_Node1.png
gatheringNode.1.frame.1=assets/images/generic/rocks/A_Rock2_Node2.png
gatheringNode.1.frame.2=assets/images/generic/rocks/A_Rock2_Node3.png
gatheringNode.1.frame.count=3
gatheringNode.1.frameDurationMs=1000
gatheringNode.1.gatherXpReward=50
gatheringNode.1.gatheringSkill=MINING
gatheringNode.1.loot.0.chance=1.0
gatheringNode.1.loot.0.itemId=custom_item_coal
gatheringNode.1.loot.count=1
gatheringNode.1.nodeId=node_coal_rock
gatheringNode.1.nodeType=MINING_ROCK
gatheringNode.1.outputItemId=custom_item_coal
gatheringNode.1.requiredLevel=30
gatheringNode.1.smeltOutputItemId=
gatheringNode.1.smeltRequiredLevel=1
gatheringNode.1.smeltXpReward=7
gatheringNode.1.visualScale=1.35
gatheringNode.2.displayName=Copper Rock
gatheringNode.2.frame.0=assets/images/generic/rocks/A_Rock1_Node1.png
gatheringNode.2.frame.1=assets/images/generic/rocks/A_Rock1_Node2.png
gatheringNode.2.frame.2=assets/images/generic/rocks/A_Rock1_Node3.png
gatheringNode.2.frame.count=3
gatheringNode.2.frameDurationMs=1000
gatheringNode.2.gatherXpReward=18
gatheringNode.2.gatheringSkill=MINING
gatheringNode.2.loot.0.chance=1.0
gatheringNode.2.loot.0.itemId=COPPER_ORE
gatheringNode.2.loot.count=1
gatheringNode.2.nodeId=node_copper_rock
gatheringNode.2.nodeType=MINING_ROCK
gatheringNode.2.outputItemId=COPPER_ORE
gatheringNode.2.requiredLevel=1
gatheringNode.2.smeltOutputItemId=COPPER_BAR
gatheringNode.2.smeltRequiredLevel=1
gatheringNode.2.smeltXpReward=7
gatheringNode.2.visualScale=1.35
gatheringNode.3.displayName=Fishing Spot
gatheringNode.3.frame.0=assets/images/monster/Nov-2015/dngn/water/shoals_shallow_water_disturbance1.png
gatheringNode.3.frame.1=assets/images/monster/Nov-2015/dngn/water/shoals_shallow_water_disturbance2.png
gatheringNode.3.frame.2=assets/images/monster/Nov-2015/dngn/water/shoals_shallow_water_disturbance3.png
gatheringNode.3.frame.count=3
gatheringNode.3.frameDurationMs=260
gatheringNode.3.gatherXpReward=18
gatheringNode.3.gatheringSkill=FISHING
gatheringNode.3.loot.0.chance=1.0
gatheringNode.3.loot.0.itemId=RAW_FISH
gatheringNode.3.loot.1.chance=0.25
gatheringNode.3.loot.1.itemId=custom_item_inert_stone
gatheringNode.3.loot.count=2
gatheringNode.3.nodeId=node_fishing_spot
gatheringNode.3.nodeType=FISHING_SPOT
gatheringNode.3.outputItemId=RAW_FISH
gatheringNode.3.requiredLevel=1
gatheringNode.3.smeltOutputItemId=
gatheringNode.3.smeltRequiredLevel=1
gatheringNode.3.smeltXpReward=0
gatheringNode.3.visualScale=1.0
gatheringNode.4.displayName=Tin Rock
gatheringNode.4.frame.0=assets/images/generic/rocks/A_Rock3_Node1.png
gatheringNode.4.frame.1=assets/images/generic/rocks/A_Rock3_Node2.png
gatheringNode.4.frame.2=assets/images/generic/rocks/A_Rock3_Node3.png
gatheringNode.4.frame.count=3
gatheringNode.4.frameDurationMs=1000
gatheringNode.4.gatherXpReward=10
gatheringNode.4.gatheringSkill=MINING
gatheringNode.4.loot.0.chance=1.0
gatheringNode.4.loot.0.itemId=custom_item_tin_ore
gatheringNode.4.loot.count=1
gatheringNode.4.nodeId=node_tin_rock
gatheringNode.4.nodeType=MINING_ROCK
gatheringNode.4.outputItemId=custom_item_tin_ore
gatheringNode.4.requiredLevel=1
gatheringNode.4.smeltOutputItemId=
gatheringNode.4.smeltRequiredLevel=1
gatheringNode.4.smeltXpReward=7
gatheringNode.4.visualScale=1.35
gatheringNode.5.displayName=Oak Tree
gatheringNode.5.frame.0=assets/images/resourceMaterial/tree.png
gatheringNode.5.frame.1=assets/images/resourceMaterial/stump.png
gatheringNode.5.frame.count=2
gatheringNode.5.frameDurationMs=1000
gatheringNode.5.gatherXpReward=18
gatheringNode.5.gatheringSkill=WOODCUTTING
gatheringNode.5.loot.0.chance=1.0
gatheringNode.5.loot.0.itemId=custom_item_oak_log
gatheringNode.5.loot.count=1
gatheringNode.5.nodeId=node_oak_tree
gatheringNode.5.nodeType=TREE
gatheringNode.5.outputItemId=custom_item_oak_log
gatheringNode.5.requiredLevel=1
gatheringNode.5.smeltOutputItemId=
gatheringNode.5.smeltRequiredLevel=1
gatheringNode.5.smeltXpReward=0
gatheringNode.5.visualScale=2.0
gatheringNode.count=6
