#Aether map design
#Fri Jul 24 21:38:24 JST 2026
limb.0.condition=PERFECT
limb.0.description=A limb taken from a Kobold
limb.0.displayName=Kobold Head
limb.0.firstPersonModelPath=
limb.0.firstPersonRigId=
limb.0.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.0.limbId=limb_kobold_head
limb.0.limbSlot=HEAD
limb.0.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.0.skillIds=WAR_CRY
limb.0.sourceCreatureId=custom_mob_kobold
limb.0.stat.AGILITY=0
limb.0.stat.ATTACK=1
limb.0.stat.DEFENSE=1
limb.0.stat.INTELLIGENCE=1
limb.0.stat.STRENGTH=0
limb.0.stat.VITALITY=0
limb.0.stat.WILLPOWER=1
limb.1.condition=PERFECT
limb.1.description=A limb taken from a Kobold
limb.1.displayName=Kobold Body
limb.1.firstPersonModelPath=
limb.1.firstPersonRigId=
limb.1.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.1.limbId=limb_kobold_body
limb.1.limbSlot=BODY
limb.1.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.1.skillIds=DEFEND
limb.1.sourceCreatureId=custom_mob_kobold
limb.1.stat.AGILITY=0
limb.1.stat.ATTACK=0
limb.1.stat.DEFENSE=1
limb.1.stat.INTELLIGENCE=0
limb.1.stat.STRENGTH=0
limb.1.stat.VITALITY=12
limb.1.stat.WILLPOWER=1
limb.10.condition=PERFECT
limb.10.description=A remnant taken from A Kobold who has attained a higher understanding after being bathed in the light of the moon.
limb.10.displayName=Kobold Wizard Body
limb.10.firstPersonModelPath=
limb.10.firstPersonRigId=
limb.10.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.10.limbId=limb_kobold_wizard_body
limb.10.limbSlot=BODY
limb.10.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.10.skillIds=
limb.10.sourceCreatureId=custom_mob_kobold_wizard
limb.10.stat.AGILITY=0
limb.10.stat.ATTACK=0
limb.10.stat.DEFENSE=1
limb.10.stat.INTELLIGENCE=0
limb.10.stat.STRENGTH=0
limb.10.stat.VITALITY=8
limb.10.stat.WILLPOWER=1
limb.11.condition=PERFECT
limb.11.description=A remnant taken from A Kobold who has attained a higher understanding after being bathed in the light of the moon.
limb.11.displayName=Kobold Wizard Legs
limb.11.firstPersonModelPath=
limb.11.firstPersonRigId=
limb.11.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.11.limbId=limb_kobold_wizard_legs
limb.11.limbSlot=LEGS
limb.11.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.11.skillIds=
limb.11.sourceCreatureId=custom_mob_kobold_wizard
limb.11.stat.AGILITY=1
limb.11.stat.ATTACK=0
limb.11.stat.DEFENSE=0
limb.11.stat.INTELLIGENCE=0
limb.11.stat.STRENGTH=0
limb.11.stat.VITALITY=2
limb.11.stat.WILLPOWER=0
limb.12.condition=PERFECT
limb.12.description=A remnant taken from A Kobold who has attained a higher understanding after being bathed in the light of the moon.
limb.12.displayName=Kobold Wizard Head
limb.12.firstPersonModelPath=
limb.12.firstPersonRigId=
limb.12.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.12.limbId=limb_kobold_wizard_head
limb.12.limbSlot=HEAD
limb.12.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.12.skillIds=FIREBALL
limb.12.sourceCreatureId=custom_mob_kobold_wizard
limb.12.stat.AGILITY=0
limb.12.stat.ATTACK=1
limb.12.stat.DEFENSE=1
limb.12.stat.INTELLIGENCE=10
limb.12.stat.STRENGTH=0
limb.12.stat.VITALITY=0
limb.12.stat.WILLPOWER=2
limb.13.condition=PERFECT
limb.13.description=A remnant taken from A Kobold who has attained a higher understanding after being bathed in the light of the moon.
limb.13.displayName=Kobold Wizard Right Arm
limb.13.firstPersonModelPath=
limb.13.firstPersonRigId=
limb.13.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.13.limbId=limb_kobold_wizard_right_arm
limb.13.limbSlot=RIGHT_ARM
limb.13.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.13.skillIds=
limb.13.sourceCreatureId=custom_mob_kobold_wizard
limb.13.stat.AGILITY=1
limb.13.stat.ATTACK=1
limb.13.stat.DEFENSE=0
limb.13.stat.INTELLIGENCE=0
limb.13.stat.STRENGTH=1
limb.13.stat.VITALITY=0
limb.13.stat.WILLPOWER=0
limb.14.condition=PERFECT
limb.14.description=A remnant taken from A Kobold who has attained a higher understanding after being bathed in the light of the moon.
limb.14.displayName=Kobold Wizard Left Arm
limb.14.firstPersonModelPath=
limb.14.firstPersonRigId=
limb.14.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.14.limbId=limb_kobold_wizard_left_arm
limb.14.limbSlot=LEFT_ARM
limb.14.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.14.skillIds=WAR_CRY
limb.14.sourceCreatureId=custom_mob_kobold_wizard
limb.14.stat.AGILITY=1
limb.14.stat.ATTACK=1
limb.14.stat.DEFENSE=0
limb.14.stat.INTELLIGENCE=0
limb.14.stat.STRENGTH=1
limb.14.stat.VITALITY=0
limb.14.stat.WILLPOWER=0
limb.15.condition=PERFECT
limb.15.description=A remnant taken from A Kobold who has grown enlarged after bathing in the moons glow for a prolonged period of time.
limb.15.displayName=Kobold Champion Head
limb.15.firstPersonModelPath=
limb.15.firstPersonRigId=
limb.15.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.15.limbId=limb_kobold_champion_head
limb.15.limbSlot=HEAD
limb.15.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.15.skillIds=
limb.15.sourceCreatureId=custom_mob_kobold_champion
limb.15.stat.AGILITY=0
limb.15.stat.ATTACK=3
limb.15.stat.DEFENSE=1
limb.15.stat.INTELLIGENCE=1
limb.15.stat.STRENGTH=0
limb.15.stat.VITALITY=0
limb.15.stat.WILLPOWER=1
limb.16.condition=PERFECT
limb.16.description=A remnant taken from A Kobold who has grown enlarged after bathing in the moons glow for a prolonged period of time.
limb.16.displayName=Kobold Champion Right Arm
limb.16.firstPersonModelPath=
limb.16.firstPersonRigId=
limb.16.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.16.limbId=limb_kobold_champion_right_arm
limb.16.limbSlot=RIGHT_ARM
limb.16.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.16.skillIds=BASH
limb.16.sourceCreatureId=custom_mob_kobold_champion
limb.16.stat.AGILITY=1
limb.16.stat.ATTACK=3
limb.16.stat.DEFENSE=0
limb.16.stat.INTELLIGENCE=0
limb.16.stat.STRENGTH=2
limb.16.stat.VITALITY=0
limb.16.stat.WILLPOWER=0
limb.17.condition=PERFECT
limb.17.description=A remnant taken from A Kobold who has grown enlarged after bathing in the moons glow for a prolonged period of time.
limb.17.displayName=Kobold Champion Body
limb.17.firstPersonModelPath=
limb.17.firstPersonRigId=
limb.17.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.17.limbId=limb_kobold_champion_body
limb.17.limbSlot=BODY
limb.17.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.17.skillIds=DEFEND
limb.17.sourceCreatureId=custom_mob_kobold_champion
limb.17.stat.AGILITY=0
limb.17.stat.ATTACK=0
limb.17.stat.DEFENSE=4
limb.17.stat.INTELLIGENCE=0
limb.17.stat.STRENGTH=0
limb.17.stat.VITALITY=16
limb.17.stat.WILLPOWER=1
limb.18.condition=PERFECT
limb.18.description=A remnant taken from A Kobold who has grown enlarged after bathing in the moons glow for a prolonged period of time.
limb.18.displayName=Kobold Champion Left Arm
limb.18.firstPersonModelPath=
limb.18.firstPersonRigId=
limb.18.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.18.limbId=limb_kobold_champion_left_arm
limb.18.limbSlot=LEFT_ARM
limb.18.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.18.skillIds=
limb.18.sourceCreatureId=custom_mob_kobold_champion
limb.18.stat.AGILITY=1
limb.18.stat.ATTACK=3
limb.18.stat.DEFENSE=0
limb.18.stat.INTELLIGENCE=0
limb.18.stat.STRENGTH=2
limb.18.stat.VITALITY=0
limb.18.stat.WILLPOWER=0
limb.19.condition=PERFECT
limb.19.description=A remnant taken from A Kobold who has grown enlarged after bathing in the moons glow for a prolonged period of time.
limb.19.displayName=Kobold Champion Legs
limb.19.firstPersonModelPath=
limb.19.firstPersonRigId=
limb.19.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.19.limbId=limb_kobold_champion_legs
limb.19.limbSlot=LEGS
limb.19.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
limb.19.skillIds=
limb.19.sourceCreatureId=custom_mob_kobold_champion
limb.19.stat.AGILITY=1
limb.19.stat.ATTACK=0
limb.19.stat.DEFENSE=0
limb.19.stat.INTELLIGENCE=0
limb.19.stat.STRENGTH=0
limb.19.stat.VITALITY=4
limb.19.stat.WILLPOWER=0
limb.2.condition=PERFECT
limb.2.description=A limb taken from a Kobold
limb.2.displayName=Kobold Left Arm
limb.2.firstPersonModelPath=
limb.2.firstPersonRigId=
limb.2.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.2.limbId=limb_kobold_left_arm
limb.2.limbSlot=LEFT_ARM
limb.2.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.2.skillIds=
limb.2.sourceCreatureId=custom_mob_kobold
limb.2.stat.AGILITY=1
limb.2.stat.ATTACK=1
limb.2.stat.DEFENSE=0
limb.2.stat.INTELLIGENCE=0
limb.2.stat.STRENGTH=1
limb.2.stat.VITALITY=0
limb.2.stat.WILLPOWER=0
limb.3.condition=PERFECT
limb.3.description=A limb taken from a Kobold
limb.3.displayName=Kobold Right Arm
limb.3.firstPersonModelPath=
limb.3.firstPersonRigId=
limb.3.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.3.limbId=limb_kobold_right_arm
limb.3.limbSlot=RIGHT_ARM
limb.3.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.3.skillIds=
limb.3.sourceCreatureId=custom_mob_kobold
limb.3.stat.AGILITY=1
limb.3.stat.ATTACK=1
limb.3.stat.DEFENSE=0
limb.3.stat.INTELLIGENCE=0
limb.3.stat.STRENGTH=1
limb.3.stat.VITALITY=0
limb.3.stat.WILLPOWER=0
limb.4.condition=PERFECT
limb.4.description=A limb taken from a Kobold
limb.4.displayName=Kobold Legs
limb.4.firstPersonModelPath=
limb.4.firstPersonRigId=
limb.4.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.4.limbId=limb_kobold_legs
limb.4.limbSlot=LEGS
limb.4.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.4.skillIds=
limb.4.sourceCreatureId=custom_mob_kobold
limb.4.stat.AGILITY=3
limb.4.stat.ATTACK=0
limb.4.stat.DEFENSE=0
limb.4.stat.INTELLIGENCE=0
limb.4.stat.STRENGTH=0
limb.4.stat.VITALITY=3
limb.4.stat.WILLPOWER=0
limb.5.condition=PERFECT
limb.5.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.5.displayName=Zombie Head
limb.5.firstPersonModelPath=
limb.5.firstPersonRigId=
limb.5.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.5.limbId=limb_zombie_head
limb.5.limbSlot=HEAD
limb.5.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.5.skillIds=
limb.5.sourceCreatureId=custom_mob_zombie
limb.5.stat.AGILITY=0
limb.5.stat.ATTACK=3
limb.5.stat.DEFENSE=1
limb.5.stat.INTELLIGENCE=1
limb.5.stat.STRENGTH=0
limb.5.stat.VITALITY=0
limb.5.stat.WILLPOWER=1
limb.6.condition=PERFECT
limb.6.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.6.displayName=Zombie Body
limb.6.firstPersonModelPath=
limb.6.firstPersonRigId=
limb.6.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.6.limbId=limb_zombie_body
limb.6.limbSlot=BODY
limb.6.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.6.skillIds=
limb.6.sourceCreatureId=custom_mob_zombie
limb.6.stat.AGILITY=0
limb.6.stat.ATTACK=0
limb.6.stat.DEFENSE=4
limb.6.stat.INTELLIGENCE=0
limb.6.stat.STRENGTH=0
limb.6.stat.VITALITY=28
limb.6.stat.WILLPOWER=1
limb.7.condition=PERFECT
limb.7.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.7.displayName=Zombie Left Arm
limb.7.firstPersonModelPath=
limb.7.firstPersonRigId=
limb.7.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.7.limbId=limb_zombie_left_arm
limb.7.limbSlot=LEFT_ARM
limb.7.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.7.skillIds=ROTTING_GRASP
limb.7.sourceCreatureId=custom_mob_zombie
limb.7.stat.AGILITY=1
limb.7.stat.ATTACK=3
limb.7.stat.DEFENSE=0
limb.7.stat.INTELLIGENCE=0
limb.7.stat.STRENGTH=5
limb.7.stat.VITALITY=0
limb.7.stat.WILLPOWER=0
limb.8.condition=PERFECT
limb.8.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.8.displayName=Zombie Right Arm
limb.8.firstPersonModelPath=
limb.8.firstPersonRigId=
limb.8.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.8.limbId=limb_zombie_right_arm
limb.8.limbSlot=RIGHT_ARM
limb.8.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.8.skillIds=
limb.8.sourceCreatureId=custom_mob_zombie
limb.8.stat.AGILITY=1
limb.8.stat.ATTACK=3
limb.8.stat.DEFENSE=0
limb.8.stat.INTELLIGENCE=0
limb.8.stat.STRENGTH=5
limb.8.stat.VITALITY=0
limb.8.stat.WILLPOWER=0
limb.9.condition=PERFECT
limb.9.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.9.displayName=Zombie Legs
limb.9.firstPersonModelPath=
limb.9.firstPersonRigId=
limb.9.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.9.limbId=limb_zombie_legs
limb.9.limbSlot=LEGS
limb.9.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.9.skillIds=
limb.9.sourceCreatureId=custom_mob_zombie
limb.9.stat.AGILITY=1
limb.9.stat.ATTACK=0
limb.9.stat.DEFENSE=0
limb.9.stat.INTELLIGENCE=0
limb.9.stat.STRENGTH=0
limb.9.stat.VITALITY=7
limb.9.stat.WILLPOWER=0
limb.count=20
