#Aether map design
#Sun Jul 19 10:19:18 JST 2026
limb.0.condition=PERFECT
limb.0.description=A limb taken from a Kobold
limb.0.displayName=Kobold Head
limb.0.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.0.limbId=limb_kobold_head
limb.0.limbSlot=HEAD
limb.0.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.0.skillIds=WAR_CRY
limb.0.sourceCreatureId=custom_mob_kobold
limb.0.stat.AGILITY=0
limb.0.stat.ATTACK=1
limb.0.stat.DEFENSE=1
limb.0.stat.INTELLIGENCE=1
limb.0.stat.STRENGTH=0
limb.0.stat.VITALITY=0
limb.0.stat.WILLPOWER=1
limb.1.condition=PERFECT
limb.1.description=A limb taken from a Kobold
limb.1.displayName=Kobold Body
limb.1.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.1.limbId=limb_kobold_body
limb.1.limbSlot=BODY
limb.1.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.1.skillIds=DEFEND
limb.1.sourceCreatureId=custom_mob_kobold
limb.1.stat.AGILITY=0
limb.1.stat.ATTACK=0
limb.1.stat.DEFENSE=1
limb.1.stat.INTELLIGENCE=0
limb.1.stat.STRENGTH=0
limb.1.stat.VITALITY=12
limb.1.stat.WILLPOWER=1
limb.2.condition=PERFECT
limb.2.description=A limb taken from a Kobold
limb.2.displayName=Kobold Left Arm
limb.2.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.2.limbId=limb_kobold_left_arm
limb.2.limbSlot=LEFT_ARM
limb.2.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.2.skillIds=
limb.2.sourceCreatureId=custom_mob_kobold
limb.2.stat.AGILITY=1
limb.2.stat.ATTACK=1
limb.2.stat.DEFENSE=0
limb.2.stat.INTELLIGENCE=0
limb.2.stat.STRENGTH=1
limb.2.stat.VITALITY=0
limb.2.stat.WILLPOWER=0
limb.3.condition=PERFECT
limb.3.description=A limb taken from a Kobold
limb.3.displayName=Kobold Right Arm
limb.3.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.3.limbId=limb_kobold_right_arm
limb.3.limbSlot=RIGHT_ARM
limb.3.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.3.skillIds=
limb.3.sourceCreatureId=custom_mob_kobold
limb.3.stat.AGILITY=1
limb.3.stat.ATTACK=1
limb.3.stat.DEFENSE=0
limb.3.stat.INTELLIGENCE=0
limb.3.stat.STRENGTH=1
limb.3.stat.VITALITY=0
limb.3.stat.WILLPOWER=0
limb.4.condition=PERFECT
limb.4.description=A limb taken from a Kobold
limb.4.displayName=Kobold Legs
limb.4.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.4.limbId=limb_kobold_legs
limb.4.limbSlot=LEGS
limb.4.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
limb.4.skillIds=
limb.4.sourceCreatureId=custom_mob_kobold
limb.4.stat.AGILITY=3
limb.4.stat.ATTACK=0
limb.4.stat.DEFENSE=0
limb.4.stat.INTELLIGENCE=0
limb.4.stat.STRENGTH=0
limb.4.stat.VITALITY=3
limb.4.stat.WILLPOWER=0
limb.5.condition=PERFECT
limb.5.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.5.displayName=Zombie Head
limb.5.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.5.limbId=limb_zombie_head
limb.5.limbSlot=HEAD
limb.5.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.5.skillIds=
limb.5.sourceCreatureId=custom_mob_zombie
limb.5.stat.AGILITY=0
limb.5.stat.ATTACK=3
limb.5.stat.DEFENSE=1
limb.5.stat.INTELLIGENCE=1
limb.5.stat.STRENGTH=0
limb.5.stat.VITALITY=0
limb.5.stat.WILLPOWER=1
limb.6.condition=PERFECT
limb.6.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.6.displayName=Zombie Body
limb.6.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.6.limbId=limb_zombie_body
limb.6.limbSlot=BODY
limb.6.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.6.skillIds=
limb.6.sourceCreatureId=custom_mob_zombie
limb.6.stat.AGILITY=0
limb.6.stat.ATTACK=0
limb.6.stat.DEFENSE=4
limb.6.stat.INTELLIGENCE=0
limb.6.stat.STRENGTH=0
limb.6.stat.VITALITY=28
limb.6.stat.WILLPOWER=1
limb.7.condition=PERFECT
limb.7.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.7.displayName=Zombie Left Arm
limb.7.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.7.limbId=limb_zombie_left_arm
limb.7.limbSlot=LEFT_ARM
limb.7.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.7.skillIds=ROTTING_GRASP
limb.7.sourceCreatureId=custom_mob_zombie
limb.7.stat.AGILITY=1
limb.7.stat.ATTACK=3
limb.7.stat.DEFENSE=0
limb.7.stat.INTELLIGENCE=0
limb.7.stat.STRENGTH=5
limb.7.stat.VITALITY=0
limb.7.stat.WILLPOWER=0
limb.8.condition=PERFECT
limb.8.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.8.displayName=Zombie Right Arm
limb.8.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.8.limbId=limb_zombie_right_arm
limb.8.limbSlot=RIGHT_ARM
limb.8.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.8.skillIds=
limb.8.sourceCreatureId=custom_mob_zombie
limb.8.stat.AGILITY=1
limb.8.stat.ATTACK=3
limb.8.stat.DEFENSE=0
limb.8.stat.INTELLIGENCE=0
limb.8.stat.STRENGTH=5
limb.8.stat.VITALITY=0
limb.8.stat.WILLPOWER=0
limb.9.condition=PERFECT
limb.9.description=A remnant taken from a Zombie, perhaps it can impart some of their strength.
limb.9.displayName=Zombie Legs
limb.9.iconPath=assets/images/monster/Ancient/Oct-5-2010/player/hand1/misc/head.png
limb.9.limbId=limb_zombie_legs
limb.9.limbSlot=LEGS
limb.9.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
limb.9.skillIds=
limb.9.sourceCreatureId=custom_mob_zombie
limb.9.stat.AGILITY=1
limb.9.stat.ATTACK=0
limb.9.stat.DEFENSE=0
limb.9.stat.INTELLIGENCE=0
limb.9.stat.STRENGTH=0
limb.9.stat.VITALITY=7
limb.9.stat.WILLPOWER=0
limb.count=10
