#Aether map design
#Fri Jul 24 21:38:24 JST 2026
mob.0.attackSoundPath=
mob.0.awarenessRadius=4
mob.0.combatAiIntelligence=10
mob.0.damageSoundPath=
mob.0.description=A Kobold, known for their pack tactics and their ability to overwhelm an enemy if caught off guard.
mob.0.displayName=Kobold
mob.0.drop.0.chance=1.0
mob.0.drop.0.itemId=custom_item_inert_stone
mob.0.drop.count=1
mob.0.imagePath=assets/images/monster/Nov-2015/mon/kobold.png
mob.0.mobId=custom_mob_kobold
mob.0.model.animation.ATTACK=assets/3D/npc/temp_kobold_basic.glb
mob.0.model.animation.ATTACK.clipName=Scratch
mob.0.model.animation.ATTACK.impactFraction=0.55
mob.0.model.animation.ATTACK.speed=1.0
mob.0.model.animation.BLOCK=assets/3D/npc/temp_kobold_basic.glb
mob.0.model.animation.BLOCK.clipName=Base_Block
mob.0.model.animation.BLOCK.impactFraction=0.55
mob.0.model.animation.BLOCK.speed=1.0
mob.0.model.animation.CAST=
mob.0.model.animation.CAST.clipName=
mob.0.model.animation.CAST.impactFraction=0.55
mob.0.model.animation.CAST.speed=1.0
mob.0.model.animation.DEATH=assets/3D/npc/temp_kobold_basic.glb
mob.0.model.animation.DEATH.clipName=Base_Death
mob.0.model.animation.DEATH.impactFraction=0.95
mob.0.model.animation.DEATH.speed=1.0
mob.0.model.animation.DODGE=
mob.0.model.animation.DODGE.clipName=
mob.0.model.animation.DODGE.impactFraction=0.55
mob.0.model.animation.DODGE.speed=1.0
mob.0.model.animation.HIT=assets/3D/npc/temp_kobold_basic.glb
mob.0.model.animation.HIT.clipName=HitReact
mob.0.model.animation.HIT.impactFraction=0.47
mob.0.model.animation.HIT.speed=1.0
mob.0.model.animation.IDLE=assets/3D/npc/generic_temp.glb
mob.0.model.animation.IDLE.clipName=Base_Idle
mob.0.model.animation.IDLE.impactFraction=0.55
mob.0.model.animation.IDLE.speed=1.0
mob.0.model.animation.WALK=assets/3D/npc/temp_kobold_basic.glb
mob.0.model.animation.WALK.clipName=Base_Walk
mob.0.model.animation.WALK.impactFraction=0.55
mob.0.model.animation.WALK.speed=1.0
mob.0.model.facingRotationDegrees=0.0
mob.0.model.path=assets/3D/npc/temp_kobold_basic.glb
mob.0.model.rigId=
mob.0.model.scale=1.0
mob.0.model.verticalOffset=0.0
mob.0.movementIntervalMs=3000
mob.0.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold_m.png
mob.0.respawnDelayMs=300000
mob.0.skillIds=DEFEND
mob.0.stat.AGILITY=5
mob.0.stat.ATTACK=2
mob.0.stat.DEFENSE=1
mob.0.stat.INTELLIGENCE=1
mob.0.stat.STRENGTH=1
mob.0.stat.VITALITY=15
mob.0.stat.WILLPOWER=1
mob.0.xpReward=10
mob.1.attackSoundPath=
mob.1.awarenessRadius=4
mob.1.combatAiIntelligence=3
mob.1.damageSoundPath=
mob.1.description=A mindless undead.
mob.1.displayName=Zombie
mob.1.drop.0.chance=0.05
mob.1.drop.0.itemId=custom_item_bronze_helmet
mob.1.drop.1.chance=1.0
mob.1.drop.1.itemId=BONES
mob.1.drop.2.chance=0.05
mob.1.drop.2.itemId=RAW_FISH
mob.1.drop.count=3
mob.1.imagePath=assets/images/monster/Nov-2015/mon/undead/ghoul.png
mob.1.mobId=custom_mob_zombie
mob.1.model.animation.ATTACK=
mob.1.model.animation.ATTACK.clipName=
mob.1.model.animation.ATTACK.impactFraction=0.55
mob.1.model.animation.ATTACK.speed=1.0
mob.1.model.animation.BLOCK=
mob.1.model.animation.BLOCK.clipName=
mob.1.model.animation.BLOCK.impactFraction=0.55
mob.1.model.animation.BLOCK.speed=1.0
mob.1.model.animation.CAST=
mob.1.model.animation.CAST.clipName=
mob.1.model.animation.CAST.impactFraction=0.55
mob.1.model.animation.CAST.speed=1.0
mob.1.model.animation.DEATH=
mob.1.model.animation.DEATH.clipName=
mob.1.model.animation.DEATH.impactFraction=0.55
mob.1.model.animation.DEATH.speed=1.0
mob.1.model.animation.DODGE=
mob.1.model.animation.DODGE.clipName=
mob.1.model.animation.DODGE.impactFraction=0.55
mob.1.model.animation.DODGE.speed=1.0
mob.1.model.animation.HIT=
mob.1.model.animation.HIT.clipName=
mob.1.model.animation.HIT.impactFraction=0.55
mob.1.model.animation.HIT.speed=1.0
mob.1.model.animation.IDLE=
mob.1.model.animation.IDLE.clipName=
mob.1.model.animation.IDLE.impactFraction=0.55
mob.1.model.animation.IDLE.speed=1.0
mob.1.model.animation.WALK=
mob.1.model.animation.WALK.clipName=
mob.1.model.animation.WALK.impactFraction=0.55
mob.1.model.animation.WALK.speed=1.0
mob.1.model.facingRotationDegrees=0.0
mob.1.model.path=
mob.1.model.rigId=
mob.1.model.scale=1.0
mob.1.model.verticalOffset=0.0
mob.1.movementIntervalMs=3000
mob.1.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/ghoul_m.png
mob.1.respawnDelayMs=300000
mob.1.skillIds=ROTTING_GRASP
mob.1.stat.AGILITY=1
mob.1.stat.ATTACK=10
mob.1.stat.DEFENSE=5
mob.1.stat.INTELLIGENCE=1
mob.1.stat.STRENGTH=10
mob.1.stat.VITALITY=35
mob.1.stat.WILLPOWER=1
mob.1.xpReward=50
mob.2.attackSoundPath=assets/sounds/generated/skelle_talk.wav
mob.2.awarenessRadius=3
mob.2.combatAiIntelligence=10
mob.2.damageSoundPath=assets/sounds/generated/sfx/Owie im dead sfx.wav
mob.2.description=A Kobold who has attained a higher understanding after being bathed in the light of the moon.
mob.2.displayName=Kobold Wizard
mob.2.drop.0.chance=0.25
mob.2.drop.0.itemId=POTION
mob.2.drop.1.chance=0.01
mob.2.drop.1.itemId=COOKED_FISH
mob.2.drop.2.chance=1.0
mob.2.drop.2.itemId=BONES
mob.2.drop.count=3
mob.2.imagePath=assets/images/monster/Nov-2015/mon/kobold_demonologist.png
mob.2.mobId=custom_mob_kobold_wizard
mob.2.model.animation.ATTACK=
mob.2.model.animation.ATTACK.clipName=
mob.2.model.animation.ATTACK.impactFraction=0.55
mob.2.model.animation.ATTACK.speed=1.0
mob.2.model.animation.BLOCK=
mob.2.model.animation.BLOCK.clipName=
mob.2.model.animation.BLOCK.impactFraction=0.55
mob.2.model.animation.BLOCK.speed=1.0
mob.2.model.animation.CAST=
mob.2.model.animation.CAST.clipName=
mob.2.model.animation.CAST.impactFraction=0.55
mob.2.model.animation.CAST.speed=1.0
mob.2.model.animation.DEATH=
mob.2.model.animation.DEATH.clipName=
mob.2.model.animation.DEATH.impactFraction=0.55
mob.2.model.animation.DEATH.speed=1.0
mob.2.model.animation.DODGE=
mob.2.model.animation.DODGE.clipName=
mob.2.model.animation.DODGE.impactFraction=0.55
mob.2.model.animation.DODGE.speed=1.0
mob.2.model.animation.HIT=
mob.2.model.animation.HIT.clipName=
mob.2.model.animation.HIT.impactFraction=0.55
mob.2.model.animation.HIT.speed=1.0
mob.2.model.animation.IDLE=
mob.2.model.animation.IDLE.clipName=
mob.2.model.animation.IDLE.impactFraction=0.55
mob.2.model.animation.IDLE.speed=1.0
mob.2.model.animation.WALK=
mob.2.model.animation.WALK.clipName=
mob.2.model.animation.WALK.impactFraction=0.55
mob.2.model.animation.WALK.speed=1.0
mob.2.model.facingRotationDegrees=0.0
mob.2.model.path=
mob.2.model.rigId=
mob.2.model.scale=1.0
mob.2.model.verticalOffset=0.0
mob.2.movementIntervalMs=2000
mob.2.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
mob.2.respawnDelayMs=300000
mob.2.skillIds=FIREBALL,WAR_CRY
mob.2.stat.AGILITY=1
mob.2.stat.ATTACK=1
mob.2.stat.DEFENSE=1
mob.2.stat.INTELLIGENCE=10
mob.2.stat.STRENGTH=1
mob.2.stat.VITALITY=10
mob.2.stat.WILLPOWER=5
mob.2.xpReward=10
mob.3.attackSoundPath=assets/sounds/generated/skelle_talk.wav
mob.3.awarenessRadius=2
mob.3.combatAiIntelligence=5
mob.3.damageSoundPath=assets/sounds/generated/sfx/Beat flesh sfx.wav
mob.3.description=A Kobold who has grown enlarged after bathing in the moons glow for a prolonged period of time.
mob.3.displayName=Kobold Champion
mob.3.drop.0.chance=0.35
mob.3.drop.0.itemId=POTION
mob.3.drop.1.chance=1.0
mob.3.drop.1.itemId=custom_item_inert_stone
mob.3.drop.2.chance=0.05
mob.3.drop.2.itemId=custom_item_iron_dagger
mob.3.drop.count=3
mob.3.imagePath=assets/images/monster/Nov-2015/mon/big_kobold.png
mob.3.mobId=custom_mob_kobold_champion
mob.3.model.animation.ATTACK=
mob.3.model.animation.ATTACK.clipName=
mob.3.model.animation.ATTACK.impactFraction=0.55
mob.3.model.animation.ATTACK.speed=1.0
mob.3.model.animation.BLOCK=
mob.3.model.animation.BLOCK.clipName=
mob.3.model.animation.BLOCK.impactFraction=0.55
mob.3.model.animation.BLOCK.speed=1.0
mob.3.model.animation.CAST=
mob.3.model.animation.CAST.clipName=
mob.3.model.animation.CAST.impactFraction=0.55
mob.3.model.animation.CAST.speed=1.0
mob.3.model.animation.DEATH=
mob.3.model.animation.DEATH.clipName=
mob.3.model.animation.DEATH.impactFraction=0.55
mob.3.model.animation.DEATH.speed=1.0
mob.3.model.animation.DODGE=
mob.3.model.animation.DODGE.clipName=
mob.3.model.animation.DODGE.impactFraction=0.55
mob.3.model.animation.DODGE.speed=1.0
mob.3.model.animation.HIT=
mob.3.model.animation.HIT.clipName=
mob.3.model.animation.HIT.impactFraction=0.55
mob.3.model.animation.HIT.speed=1.0
mob.3.model.animation.IDLE=
mob.3.model.animation.IDLE.clipName=
mob.3.model.animation.IDLE.impactFraction=0.55
mob.3.model.animation.IDLE.speed=1.0
mob.3.model.animation.WALK=
mob.3.model.animation.WALK.clipName=
mob.3.model.animation.WALK.impactFraction=0.55
mob.3.model.animation.WALK.speed=1.0
mob.3.model.facingRotationDegrees=0.0
mob.3.model.path=
mob.3.model.rigId=
mob.3.model.scale=1.0
mob.3.model.verticalOffset=0.0
mob.3.movementIntervalMs=2000
mob.3.paperDollSourcePath=assets/images/monster/Nov-2015/player/base/kobold2_m.png
mob.3.respawnDelayMs=300000
mob.3.skillIds=DEFEND,BASH
mob.3.stat.AGILITY=1
mob.3.stat.ATTACK=10
mob.3.stat.DEFENSE=5
mob.3.stat.INTELLIGENCE=1
mob.3.stat.STRENGTH=5
mob.3.stat.VITALITY=20
mob.3.stat.WILLPOWER=1
mob.3.xpReward=35
mob.count=4
