#Aether map design
#Mon Jul 20 19:08:41 JST 2026
npc.0.displayName=Ghost
npc.0.imagePath=assets/images/monster/Nov-2015/mon/undead/missing_ghost.png
npc.0.interactionId=authored_dialogue_new_npc
npc.0.npcId=npc_custom_npc
npc.0.shop.enabled=false
npc.0.talkSoundPath=assets/sounds/generated/ghost-talk.wav
npc.1.displayName=Jib
npc.1.imagePath=assets/images/monster/Nov-2015/mon/unique/ijyb.png
npc.1.interactionId=
npc.1.npcId=npc_jib
npc.1.shop.enabled=true
npc.1.shop.greeting=Take a look at my wares.
npc.1.shop.name=Jib's Totally new Items
npc.1.shop.stock.0.buyPrice=-1
npc.1.shop.stock.0.itemId=COOKED_FISH
npc.1.shop.stock.0.quantity=10
npc.1.shop.stock.0.sellPrice=-1
npc.1.shop.stock.1.buyPrice=-1
npc.1.shop.stock.1.itemId=custom_item_steel_bar
npc.1.shop.stock.1.quantity=1
npc.1.shop.stock.1.sellPrice=-1
npc.1.shop.stock.2.buyPrice=-1
npc.1.shop.stock.2.itemId=LEATHER_CAP
npc.1.shop.stock.2.quantity=5
npc.1.shop.stock.2.sellPrice=-1
npc.1.shop.stock.count=3
npc.1.talkSoundPath=assets/sounds/generated/ghost-talk.wav
npc.2.displayName=Villager
npc.2.imagePath=assets/images/monster/Nov-2015/mon/halfling.png
npc.2.interactionId=authored_dialogue_villager
npc.2.npcId=npc_villager
npc.2.shop.enabled=false
npc.2.talkSoundPath=assets/sounds/generated/chitter.wav
npc.3.displayName=Nired
npc.3.imagePath=assets/images/monster/Nov-2015/mon/unique/josephine.png
npc.3.interactionId=authored_dialogue_nired_s_quest
npc.3.npcId=npc_nired
npc.3.shop.enabled=false
npc.3.talkSoundPath=
npc.count=4
