#Aether map design
#Thu Jul 23 21:45:24 JST 2026
npc.0.displayName=Ghost
npc.0.imagePath=assets/images/monster/Nov-2015/mon/undead/missing_ghost.png
npc.0.interactionId=authored_dialogue_new_npc
npc.0.model.animation.ATTACK=
npc.0.model.animation.ATTACK.clipName=
npc.0.model.animation.ATTACK.impactFraction=0.55
npc.0.model.animation.ATTACK.speed=1.0
npc.0.model.animation.BLOCK=
npc.0.model.animation.BLOCK.clipName=
npc.0.model.animation.BLOCK.impactFraction=0.55
npc.0.model.animation.BLOCK.speed=1.0
npc.0.model.animation.CAST=
npc.0.model.animation.CAST.clipName=
npc.0.model.animation.CAST.impactFraction=0.55
npc.0.model.animation.CAST.speed=1.0
npc.0.model.animation.DEATH=
npc.0.model.animation.DEATH.clipName=
npc.0.model.animation.DEATH.impactFraction=0.55
npc.0.model.animation.DEATH.speed=1.0
npc.0.model.animation.DODGE=
npc.0.model.animation.DODGE.clipName=
npc.0.model.animation.DODGE.impactFraction=0.55
npc.0.model.animation.DODGE.speed=1.0
npc.0.model.animation.HIT=
npc.0.model.animation.HIT.clipName=
npc.0.model.animation.HIT.impactFraction=0.55
npc.0.model.animation.HIT.speed=1.0
npc.0.model.animation.IDLE=
npc.0.model.animation.IDLE.clipName=
npc.0.model.animation.IDLE.impactFraction=0.55
npc.0.model.animation.IDLE.speed=1.0
npc.0.model.animation.WALK=
npc.0.model.animation.WALK.clipName=
npc.0.model.animation.WALK.impactFraction=0.55
npc.0.model.animation.WALK.speed=1.0
npc.0.model.facingRotationDegrees=0.0
npc.0.model.path=
npc.0.model.rigId=
npc.0.model.scale=1.0
npc.0.model.verticalOffset=0.0
npc.0.npcId=npc_custom_npc
npc.0.shop.enabled=false
npc.0.talkSoundPath=assets/sounds/generated/ghost-talk.wav
npc.1.displayName=Jib
npc.1.imagePath=assets/images/monster/Nov-2015/mon/unique/ijyb.png
npc.1.interactionId=
npc.1.model.animation.ATTACK=
npc.1.model.animation.ATTACK.clipName=
npc.1.model.animation.ATTACK.impactFraction=0.55
npc.1.model.animation.ATTACK.speed=1.0
npc.1.model.animation.BLOCK=
npc.1.model.animation.BLOCK.clipName=
npc.1.model.animation.BLOCK.impactFraction=0.55
npc.1.model.animation.BLOCK.speed=1.0
npc.1.model.animation.CAST=
npc.1.model.animation.CAST.clipName=
npc.1.model.animation.CAST.impactFraction=0.55
npc.1.model.animation.CAST.speed=1.0
npc.1.model.animation.DEATH=
npc.1.model.animation.DEATH.clipName=
npc.1.model.animation.DEATH.impactFraction=0.55
npc.1.model.animation.DEATH.speed=1.0
npc.1.model.animation.DODGE=
npc.1.model.animation.DODGE.clipName=
npc.1.model.animation.DODGE.impactFraction=0.55
npc.1.model.animation.DODGE.speed=1.0
npc.1.model.animation.HIT=
npc.1.model.animation.HIT.clipName=
npc.1.model.animation.HIT.impactFraction=0.55
npc.1.model.animation.HIT.speed=1.0
npc.1.model.animation.IDLE=
npc.1.model.animation.IDLE.clipName=
npc.1.model.animation.IDLE.impactFraction=0.55
npc.1.model.animation.IDLE.speed=1.0
npc.1.model.animation.WALK=
npc.1.model.animation.WALK.clipName=
npc.1.model.animation.WALK.impactFraction=0.55
npc.1.model.animation.WALK.speed=1.0
npc.1.model.facingRotationDegrees=0.0
npc.1.model.path=
npc.1.model.rigId=
npc.1.model.scale=1.0
npc.1.model.verticalOffset=0.0
npc.1.npcId=npc_jib
npc.1.shop.enabled=true
npc.1.shop.greeting=Take a look at my wares.
npc.1.shop.name=Jib's Totally new Items
npc.1.shop.stock.0.buyPrice=-1
npc.1.shop.stock.0.itemId=COOKED_FISH
npc.1.shop.stock.0.quantity=10
npc.1.shop.stock.0.sellPrice=-1
npc.1.shop.stock.1.buyPrice=-1
npc.1.shop.stock.1.itemId=custom_item_steel_bar
npc.1.shop.stock.1.quantity=1
npc.1.shop.stock.1.sellPrice=-1
npc.1.shop.stock.2.buyPrice=-1
npc.1.shop.stock.2.itemId=LEATHER_CAP
npc.1.shop.stock.2.quantity=5
npc.1.shop.stock.2.sellPrice=-1
npc.1.shop.stock.count=3
npc.1.talkSoundPath=assets/sounds/generated/ghost-talk.wav
npc.2.displayName=Villager
npc.2.imagePath=assets/images/monster/Nov-2015/mon/halfling.png
npc.2.interactionId=authored_dialogue_villager
npc.2.model.animation.ATTACK=
npc.2.model.animation.ATTACK.clipName=
npc.2.model.animation.ATTACK.impactFraction=0.55
npc.2.model.animation.ATTACK.speed=1.0
npc.2.model.animation.BLOCK=
npc.2.model.animation.BLOCK.clipName=
npc.2.model.animation.BLOCK.impactFraction=0.55
npc.2.model.animation.BLOCK.speed=1.0
npc.2.model.animation.CAST=
npc.2.model.animation.CAST.clipName=
npc.2.model.animation.CAST.impactFraction=0.55
npc.2.model.animation.CAST.speed=1.0
npc.2.model.animation.DEATH=
npc.2.model.animation.DEATH.clipName=
npc.2.model.animation.DEATH.impactFraction=0.55
npc.2.model.animation.DEATH.speed=1.0
npc.2.model.animation.DODGE=
npc.2.model.animation.DODGE.clipName=
npc.2.model.animation.DODGE.impactFraction=0.55
npc.2.model.animation.DODGE.speed=1.0
npc.2.model.animation.HIT=
npc.2.model.animation.HIT.clipName=
npc.2.model.animation.HIT.impactFraction=0.55
npc.2.model.animation.HIT.speed=1.0
npc.2.model.animation.IDLE=
npc.2.model.animation.IDLE.clipName=
npc.2.model.animation.IDLE.impactFraction=0.55
npc.2.model.animation.IDLE.speed=1.0
npc.2.model.animation.WALK=
npc.2.model.animation.WALK.clipName=
npc.2.model.animation.WALK.impactFraction=0.55
npc.2.model.animation.WALK.speed=1.0
npc.2.model.facingRotationDegrees=0.0
npc.2.model.path=
npc.2.model.rigId=
npc.2.model.scale=1.0
npc.2.model.verticalOffset=0.0
npc.2.npcId=npc_villager
npc.2.shop.enabled=false
npc.2.talkSoundPath=assets/sounds/generated/chitter.wav
npc.3.displayName=Nired
npc.3.imagePath=assets/images/monster/Nov-2015/mon/unique/josephine.png
npc.3.interactionId=authored_dialogue_nired_s_quest
npc.3.model.animation.ATTACK=
npc.3.model.animation.ATTACK.clipName=
npc.3.model.animation.ATTACK.impactFraction=0.55
npc.3.model.animation.ATTACK.speed=1.0
npc.3.model.animation.BLOCK=
npc.3.model.animation.BLOCK.clipName=
npc.3.model.animation.BLOCK.impactFraction=0.55
npc.3.model.animation.BLOCK.speed=1.0
npc.3.model.animation.CAST=
npc.3.model.animation.CAST.clipName=
npc.3.model.animation.CAST.impactFraction=0.55
npc.3.model.animation.CAST.speed=1.0
npc.3.model.animation.DEATH=
npc.3.model.animation.DEATH.clipName=
npc.3.model.animation.DEATH.impactFraction=0.55
npc.3.model.animation.DEATH.speed=1.0
npc.3.model.animation.DODGE=
npc.3.model.animation.DODGE.clipName=
npc.3.model.animation.DODGE.impactFraction=0.55
npc.3.model.animation.DODGE.speed=1.0
npc.3.model.animation.HIT=
npc.3.model.animation.HIT.clipName=
npc.3.model.animation.HIT.impactFraction=0.55
npc.3.model.animation.HIT.speed=1.0
npc.3.model.animation.IDLE=
npc.3.model.animation.IDLE.clipName=
npc.3.model.animation.IDLE.impactFraction=0.55
npc.3.model.animation.IDLE.speed=1.0
npc.3.model.animation.WALK=
npc.3.model.animation.WALK.clipName=
npc.3.model.animation.WALK.impactFraction=0.55
npc.3.model.animation.WALK.speed=1.0
npc.3.model.facingRotationDegrees=0.0
npc.3.model.path=
npc.3.model.rigId=
npc.3.model.scale=1.0
npc.3.model.verticalOffset=0.0
npc.3.npcId=npc_nired
npc.3.shop.enabled=false
npc.3.talkSoundPath=
npc.count=4
