#Aether map design
#Fri Jul 24 22:42:02 JST 2026
quest.0.displayName=a Warrior's Guidance
quest.0.questId=authored_quest_a_warrior_s_guidance
quest.0.stage.0=Speak to warrior.
quest.0.stage.1=Fish a fish and return to the warrior.
quest.0.stage.2=Cook the fish on the fireplace and return to the warrior.
quest.0.stage.3=Mine the copper mine.
quest.0.stage.4=Create a Copper Dagger.
quest.0.stage.5=Kill a Kobold
quest.0.stage.6=Completed.
quest.0.stage.count=7
quest.1.displayName=A Quest of Vengence
quest.1.questId=authored_quest_a_quest_of_vengence
quest.1.stage.0=Find Nired (Have to be able to defeat a level 7 creature).
quest.1.stage.1=Go to the Catacombs east of the city. and Bring back the bones of the Wizard.
quest.1.stage.2=Complete
quest.1.stage.count=3
quest.count=2
