#Aether data-driven battle statuses
#Thu Aug 06 04:52:19 JST 2026
schemaVersion=2
status.0.behaviorKind=periodic_health
status.0.defaultDuration=5
status.0.description=A basic poison.
status.0.displayName=Basic Poison
status.0.iconPath=assets/images/monster/Nov-2015/effect/cloud_poison0.png
status.0.id=basic_poison
status.0.maxStacks=1
status.0.param.magnitude=-2
status.0.polarity=HARMFUL
status.0.stackingPolicy=REPLACE
status.1.behaviorKind=incoming_damage_modifier
status.1.defaultDuration=2
status.1.description=Incoming damage is reduced.
status.1.displayName=Guarded
status.1.iconPath=assets/images/ui/01_UI_Resources/A1ICON/Shield.png
status.1.id=guard
status.1.maxStacks=1
status.1.param.percent=-50
status.1.polarity=BENEFICIAL
status.1.stackingPolicy=REFRESH
status.2.behaviorKind=stat_modifier
status.2.defaultDuration=2
status.2.description=Agility is reduced by rotting flesh.
status.2.displayName=Rotting
status.2.iconPath=assets/images/ui/01_UI_Resources/A1ICON/Weakness.png
status.2.id=rotting_grasp
status.2.maxStacks=1
status.2.param.magnitude=-2
status.2.param.stat=AGILITY
status.2.polarity=HARMFUL
status.2.stackingPolicy=REFRESH
status.3.behaviorKind=action_lock
status.3.defaultDuration=1
status.3.description=Cannot act while stunned.
status.3.displayName=Stun
status.3.iconPath=assets/images/ui/01_UI_Resources/A1ICON/icon_ban.png
status.3.id=stun
status.3.maxStacks=1
status.3.param.magnitude=0
status.3.polarity=HARMFUL
status.3.stackingPolicy=REFRESH
status.count=4
